import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, BookOpen, Library } from "lucide-react";
import glassDossier from "@/assets/glass-dossier.jpg";

import { SiteShell, StatusBadge } from "@/components/site-shell";
import { claims } from "@/lib/dossier-data";

export const Route = createFileRoute("/")({head:()=>({meta:[{title:"De Marktplaats van de Ziel — Onderzoeksportaal"},{name:"description",content:"Een forensische Hexalogie over de commerciële infrastructuur van digitale intimiteit."},{property:"og:title",content:"De Marktplaats van de Ziel"},{property:"og:description",content:"Zes onderzoekspijlers en één centrale bibliotheek voor controle, beleid en herstel."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:HomePage});

function HomePage(){return <SiteShell><main>
  <section className="manifest-hero"><img src={glassDossier} alt="Glazen archieflagen als beeld voor verborgen digitale infrastructuur"/><div className="manifest-image-shade"/><div className="manifest-copy"><p className="edition-line"><span>Hexalogie</span><span>Systeemanalyse</span><span>Record · 2026</span></p><h1>De Marktplaats<br/>van de <em>Ziel</em></h1><p className="manifest-subtitle">Zes boeken · één forensisch onderzoek</p><blockquote>“Wie spreekt, wie stuurt en wie verdient wanneer intimiteit infrastructuur wordt?”</blockquote><div className="hero-actions"><Link to="/onderzoek" className="primary-action"><BookOpen/>Open het onderzoek</Link><Link to="/archief" className="secondary-action">Naar de Bibliotheek <ArrowRight/></Link></div></div><a href="#inleiding" className="scroll-cue"><ArrowDown/>Lees verder</a></section>
  <section id="inleiding" className="manifest-intro"><div><p className="eyebrow text-alert">Het kernonderzoek</p><h2>Een persoonlijke interface kan een industriële achterkant hebben.</h2></div><div><p>De Hexalogie onderzoekt de technische, financiële, psychologische, sociologische en juridische architectuur achter betaalde digitale intimiteit — en de routes naar herstel.</p><dl><div><dt>06</dt><dd>onderzoeksboeken</dd></div><div><dt>01</dt><dd>pers-whitepaper</dd></div><div><dt>01</dt><dd>centrale bibliotheek</dd></div></dl></div></section>
  <section className="three-doors"><header><p className="eyebrow">Drie duidelijke routes</p><h2>Onderzoek, publicaties en wetgeving zonder doublures.</h2></header><div><Link to="/onderzoek"><code>01 · INHOUD</code><h3>De zes pijlers</h3><p>Van CRM en carding tot neurobiologie, demografie, recht en herstel.</p><ArrowRight/></Link><Link to="/archief"><code>02 · PUBLICATIES</code><h3>De Bibliotheek</h3><p>De enige downloadplek voor de zes boeken en de pers-whitepaper.</p><ArrowRight/></Link><Link to="/juridisch"><code>03 · KADER</code><h3>Lex Humanitas Digitalis</h3><p>Bestaand recht en een toetsbaar model voor identiteitstransparantie.</p><ArrowRight/></Link></div></section>
  <section className="claim-ledger"><div><p className="eyebrow text-alert">Bewijs boven bewering</p><h2>Iedere centrale claim draagt haar eigen gewicht.</h2><Link to="/claims" className="text-link">Bekijk het volledige register <ArrowRight/></Link></div><div>{claims.slice(0,4).map(c=><article key={c.id}><div><code>{c.id}</code><StatusBadge status={c.status}/></div><h3>{c.title}</h3><p>{c.sources.length?`${c.sources.length} gekoppelde bron${c.sources.length>1?'nen':''}`:"Geen bevestigende bron"}</p></article>)}</div></section>
  <section className="publication-band"><div><p className="eyebrow">Definitieve reeks · 2026</p><h2>Zeven publicaties. Eén gecontroleerde plek.</h2><p>De Bibliotheek bevat uitsluitend Boek I–VI en de pers-whitepaper, met actuele metadata en vaste PDF-uitgaven.</p></div><div className="publication-actions"><Link to="/archief" className="primary-action"><Library/> Open de Bibliotheek <ArrowRight/></Link></div></section>
  </main></SiteShell>}