# -*- coding: utf-8 -*-
"""Boek VI — Het post-digitale verzet. Praktische protocollen en het manifest."""

CHAPTERS = [

{"num": "01", "part": "DEEL I — PROTOCOLLEN",
 "title": "Protocol voor de gedupeerde koper",
 "deck": "Wie ontdekt dat hij betaalde voor gesprekken met iemand anders dan hij dacht, heeft een korte periode waarin bewijs nog bestaat. Dit hoofdstuk is een handelingsvolgorde, geen troost.",
 "blocks": [
  ("h3", "Stap 1 — Bewijs vastleggen vóór opzegging"),
  ("p", "Zeg niets op en verwijder niets voordat het gesprek is veiliggesteld. Na opzegging vervalt in veel gevallen de toegang tot de berichtengeschiedenis. Maak volledige schermafdrukken met zichtbare datum en tijd, exporteer waar het platform dat aanbiedt, en bewaar de bankafschrijvingen met omschrijving, bedrag en datum in één map."),
  ("h3", "Stap 2 — Het inzageverzoek"),
  ("p", "Onder artikel 15 AVG heeft iedere betrokkene recht op inzage in de persoonsgegevens die over hem worden verwerkt, inclusief de ontvangers en het doel. [BR-32] Dat recht geldt tegenover het platform én tegenover het beheerbureau, voor zover dat bureau als verwerkingsverantwoordelijke of verwerker optreedt. Een inzageverzoek is kosteloos en moet binnen één maand worden beantwoord."),
  ("box", "Modeltekst inzageverzoek",
   "‘Op grond van artikel 15 AVG verzoek ik om inzage in alle persoonsgegevens die u over mij verwerkt, waaronder gespreksnotities, classificaties, segmenten en scores, alsmede om opgave van de ontvangers van deze gegevens en van de verwerkingsdoeleinden. Ik verzoek tevens om mededeling of bij de communicatie met mij geautomatiseerde systemen of derden zijn ingezet.’"),
  ("h3", "Stap 3 — De betaalroute"),
  ("p", "Bij niet-toegestane transacties biedt PSD2 een terugbetalingsrecht, met de bewijslast voor autorisatie bij de betaaldienstverlener. [BR-45] Bij wél geautoriseerde maar mogelijk misleidend tot stand gekomen betalingen is de route civielrechtelijk: het geschil gaat dan over de vraag wat is voorgesteld. Boek II beschrijft waarom die vraag zo moeilijk ligt."),
  ("h3", "Stap 4 — De melding"),
  ("p", "Meld bij de nationale consumentenautoriteit en, waar het om gegevensverwerking gaat, bij de gegevensbeschermingsautoriteit. Vermeld feitelijk wat is waargenomen, met data en bedragen, zonder conclusies over strafbaarheid. Een melding met documenten weegt zwaarder dan tien meldingen zonder."),
  ("box", "Bewijsgrens",
   "Dit protocol is geen juridisch advies en geeft geen garantie op resultaat. Het beschrijft bestaande rechten en de volgorde waarin het gebruik ervan praktisch het meest kans maakt."),
 ]},

{"num": "02", "part": "DEEL I — PROTOCOLLEN",
 "title": "Protocol voor de creator: sanering van het contract",
 "deck": "Drie bepalingen bepalen of een samenwerking een dienstverlening is of een overname. Wie ze kent, kan ze toetsen voordat hij tekent — en aanvechten nadat hij tekende.",
 "blocks": [
  ("h3", "De drie kernbepalingen"),
  ("ul", ["Toegang: wie beheert het wachtwoord, het e-mailadres en de tweefactorherstelcodes? Uitsluitend de creator — elke andere afspraak is een overdracht van zeggenschap.",
          "Uitbetaling: op wiens rekening komt de platformuitbetaling binnen? Uitsluitend op de rekening van de creator, met doorbetaling van commissie aan het bureau, nooit omgekeerd.",
          "Beëindiging: welke opzegtermijn geldt, en welke boete? Een termijn van meer dan drie maanden of een boete die het jaarinkomen benadert, verstoort het evenwicht wezenlijk."]),
  ("p", "Bedingen die het evenwicht tussen partijen aanzienlijk verstoren ten nadele van de consument zijn onder Europees recht toetsbaar en kunnen nietig zijn. [BR-46] [CL-28] Waar de creator als particulier toetreedt zonder onderneming, is die toets een reële route en geen theoretische."),
  ("h3", "Gegevens terugvorderen"),
  ("p", "De creator heeft daarnaast eigen AVG-rechten tegenover het bureau: inzage in de gegevens die over abonnees onder haar naam zijn vastgelegd, en de vraag wie daarvoor verwerkingsverantwoordelijke is. [BR-32] Die vraag is niet retorisch: het antwoord bepaalt wie aansprakelijk is wanneer die dossiers uitlekken."),
  ("box", "Wanneer het geen contractkwestie meer is",
   "Wanneer toegang wordt afgenomen, uitbetaling wordt geblokkeerd of er wordt gedreigd met publicatie van materiaal, is het geen commercieel geschil maar mogelijk een strafbaar feit. In gedocumenteerde gevallen leidde dit tot vervolging. [BR-05] [BR-17] Leg de dreiging vast en meld haar."),
 ]},

{"num": "03", "part": "DEEL I — PROTOCOLLEN",
 "title": "Protocol voor de chatter",
 "deck": "De laagstbetaalde schakel draagt het grootste morele gewicht en heeft de minste bescherming. Dit hoofdstuk beschrijft wat er wél mogelijk is.",
 "blocks": [
  ("p", "Chatters werken doorgaans buiten de EU, vaak zonder arbeidsovereenkomst, en worden betaald per bericht of op commissie. [BR-06] [BR-19] [BR-20] Hun juridische positie is zwak, hun bewijspositie niet. Alles wat zij doen, verloopt via systemen die loggen."),
  ("h3", "Wat te bewaren"),
  ("ul", ["Het trainingsmateriaal en de gespreksinstructies, met datum van ontvangst.",
          "De roosters en de uitbetalingsoverzichten per periode.",
          "Instructies die aansturen op verzwijgen van de eigen rol, en instructies over kwetsbare abonnees.",
          "Communicatie waarin druk of dreiging wordt uitgeoefend."]),
  ("p", "Die documenten vormen het materiaal waarop journalistiek onderzoek en toezicht tot dusver hebben gedraaid. Vier redacties hebben op precies dit soort materiaal de sector in kaart gebracht. [BR-07] [BR-15] [BR-16] [BR-06]"),
  ("box", "Veiligheid eerst",
   "Bewijs verzamelen brengt risico mee voor wie afhankelijk is van het inkomen. Dit dossier roept niemand op tot handelingen die zijn positie in gevaar brengen. Waar publicatie te riskant is, bestaan er redacties en toezichthouders die vertrouwelijk materiaal aannemen."),
 ]},

{"num": "04", "part": "DEEL II — HERSTEL",
 "title": "Onbetaalde gemeenschap als tegenvoorstel",
 "deck": "Regulering corrigeert het aanbod. Zij vult niets aan. Het tweede deel van het antwoord ligt buiten het recht.",
 "blocks": [
  ("p", "De vraag waarop deze bedrijfstak antwoordt — aandacht, erkenning, iemand die je naam kent — is echt. Boek IV stelde vast dat er een grote betalende vraag naar is en dat de oorzaak daarvan niet met zekerheid is toe te schrijven. Wat wel vaststaat, is dat een betaald antwoord op die vraag per definitie eindigt bij het opzeggen van de betaling."),
  ("p", "Het alternatief is niet romantisch en niet nieuw: verbanden waarin contact geen prijs heeft. Verenigingen, koren, sportclubs, buurtinitiatieven, vrijwilligerswerk, plekken waar aanwezigheid genoeg is. Hun kenmerkende eigenschap is niet dat ze analoog zijn, maar dat de relatie niet verdwijnt wanneer het geld stopt."),
  ("box", "Feit, interpretatie, voorstel",
   "Feit: betaald contact eindigt bij beëindiging van de betaling. Interpretatie: dat maakt het structureel ongeschikt als antwoord op langdurige eenzaamheid. Voorstel: beleid dat de vraagzijde adresseert — betaalbare ruimte voor verenigingen, werktijden die contact toelaten — hoort bij elk voorstel dat het aanbod reguleert."),
  ("h2", "Geen technologiekritiek"),
  ("p", "Dit is geen pleidooi tegen digitaal contact. Het onderscheid dat ertoe doet, loopt niet tussen scherm en ontmoeting, maar tussen contact waarvan je weet wie er aan de andere kant zit en contact waarvan je dat niet weet. Het hele dossier draait om dat ene onderscheid."),
 ]},

{"num": "05", "part": "DEEL II — HERSTEL",
 "title": "Het post-digitale manifest",
 "deck": "Zes uitgangspunten. Geen ideologie, geen beweging, geen oproep tot boycot — alleen wat uit de voorgaande vijf boeken volgt.",
 "blocks": [
  ("h3", "I. Wie schrijft, wordt genoemd"),
  ("p", "Bij betaald persoonlijk contact heeft de betalende partij recht op de mededeling of de tekst afkomstig is van de genoemde persoon, van een medewerker, of van een geautomatiseerd systeem. Die mededeling is niet belastend en niet duur; haar afwezigheid is een keuze."),
  ("h3", "II. Intimiteit is geen dossier"),
  ("p", "Wat iemand in een als persoonlijk gepresenteerd gesprek vertelt over rouw, relaties of gezondheid, is geen bedrijfsmiddel. Bijzondere categorieën persoonsgegevens verdienen hier dezelfde bescherming als elders. [BR-32]"),
  ("h3", "III. Wie de opbrengst neemt, draagt de verantwoordelijkheid"),
  ("p", "Een partij die de gespreksvoering organiseert en er het grootste deel van de opbrengst uit haalt, kan zich niet verschuilen achter de naam op het account. Ketenaansprakelijkheid is hier de enige werkbare toerekening."),
  ("h3", "IV. Ontwerp dat bindt, valt onder toezicht"),
  ("p", "Wat in kansspelen en in games met aankopen als risico-ontwerp wordt behandeld, verdient hier dezelfde behandeling: uitgavenoverzicht, plafondmogelijkheid, afkoelingsmoment."),
  ("h3", "V. Het bewijs blijft bij de koper"),
  ("p", "Gespreksgeschiedenis en betaalgegevens moeten exporteerbaar zijn en na beëindiging toegankelijk blijven. Zonder bewijs is elk recht theoretisch."),
  ("h3", "VI. Twijfel wordt uitgesproken, niet verborgen"),
  ("p", "Wie een misstand aanklaagt, markeert wat hij niet weet. Dit dossier doet dat in elk hoofdstuk, en verwacht hetzelfde van wie het weerspreekt."),
 ]},

{"num": "06", "part": "DEEL III — VERANTWOORDING",
 "title": "Wat er moet gebeuren, en door wie",
 "deck": "Sluitstuk: de adressering. Elk voorstel uit deze zes boeken, gekoppeld aan de partij die het kan uitvoeren.",
 "blocks": [
  ("table", [["Maatregel", "Adres", "Bestaand instrument"],
             ["Mededelingsplicht over wie schrijft", "Uniewetgever", "Nieuw — Boek V"],
             ["Handhaving misleidende praktijk", "Consumentenautoriteiten", "UCPD, art. 6–7 [BR-31]"],
             ["Toetsing bureaucontracten", "Consumentenautoriteiten", "Richtlijn 93/13/EEG [BR-46]"],
             ["Inzage- en exportrecht afdwingen", "Gegevensbeschermingsautoriteiten", "AVG, art. 15 [BR-32]"],
             ["Risicobeoordeling van gespreksontwerp", "Platformen", "DSA, art. 34–35 [BR-33]"],
             ["Melding bij AI-interactie", "Aanbieders", "AI-verordening, art. 50 [BR-34]"],
             ["Meten van substitutie-effecten", "Statistiekbureaus", "Tijdsbestedingsonderzoek [BR-43]"]],
   [40, 30, 30]),
  ("p", "Zes van de zeven maatregelen vergen geen nieuwe wetgeving. Dat is de belangrijkste bevinding van deze hexalogie: het grootste deel van het probleem is niet ongeregeld, maar ongehandhaafd. De enige echt nieuwe regel is de eerste — en die is de kortste."),
  ("box", "Wederhoor en correcties",
   "Deze uitgaven zijn gebaseerd op openbare bronnen. Er is geen wederhoor toegepast bij individuele bureaus of personen; er worden in deze boeken dan ook geen individuele beschuldigingen geuit die niet reeds door een genoemde redactie of rechter zijn gepubliceerd. Correcties worden opgenomen in het publieke correctieregister en in de versiegeschiedenis van de website."),
  ("p", "Daarmee sluit het dossier. Niet met een oproep, maar met een controleerbare lijst. Wie haar wil weerleggen, heeft de bronnen erbij."),
 ]},
]
