# -*- coding: utf-8 -*-
"""Boek II — De financiële schaduweconomie. Zelfde blokgrammatica als chapters.py."""

CHAPTERS = [

{"num": "01", "part": "DEEL I — DE ROUTE VAN HET GELD",
 "title": "De weg van één euro",
 "deck": "Volg één betaling van abonnee tot ontvanger. De route is kort, maar elke stap heeft een eigen rechtsverhouding, een eigen inhouding en een eigen mate van zichtbaarheid.",
 "blocks": [
  ("p", "Een abonnee betaalt met een bankkaart. Die betaling raakt achtereenvolgens een betaaldienstverlener, het platform, mogelijk een beheerbureau, en pas daarna de persoon op wiens naam het account staat. Elke schakel houdt iets in en legt iets vast. De abonnee ziet één afschrijving en één afzender; hij ziet de keten niet. Dat verschil tussen wat er gebeurt en wat er zichtbaar is, is het onderwerp van dit boek."),
  ("p", "De eerste inhouding is de bekendste: het platform houdt twintig procent van elke betaling in. Op de 7,22 miljard dollar aan fanbetalingen in boekjaar 2024 leverde dat een netto-omzet van 1,41 miljard dollar op, met 684 miljoen dollar winst voor belasting en 497 miljoen dollar dividend aan de aandeelhouder. [BR-35] [BR-37] Deze inhouding staat in de voorwaarden en is voor beide zijden kenbaar."),
  ("p", "De tweede inhouding staat nergens voor de abonnee. Het beheerbureau neemt volgens de BBC gemiddeld de helft van wat overblijft [BR-05]; Duits onderzoek documenteerde contracten waarin het bureau tot twee derde ontving [BR-14]. Balkan Insight beschreef een creator die op een bruto-opbrengst van 178.000 dollar zelf 10.000 dollar ontving. [BR-22] Voor de betalende abonnee is die verdeling onzichtbaar, en zij verandert de aard van zijn betaling: het grootste deel gaat niet naar de persoon aan wie hij denkt te betalen."),
  ("table", [["Schakel", "Typische inhouding", "Zichtbaar voor de abonnee"],
             ["Betaaldienstverlener", "1–6 % + vaste kosten", "Nee"],
             ["Platform", "20 %", "Ja, in de voorwaarden"],
             ["Beheerbureau", "40–66 %", "Nee"],
             ["Creator", "restbedrag", "Verondersteld het geheel"]],
   [34, 33, 33]),
  ("box", "Bewijsgrens",
   "De platformcijfers komen uit gedeponeerde jaarrekeningen. De bureaupercentages komen uit journalistiek gedocumenteerde individuele contracten en zijn geen sectorgemiddelde. De tabel toont ordes van grootte, geen meting. De kolom betaaldienstverlener is een marktbandbreedte, geen bedrijfsspecifiek tarief."),
  ("h2", "Waarom de verdeling het gesprek stuurt"),
  ("p", "Wie de helft of meer van de opbrengst ontvangt zonder het beeldmateriaal te maken, verdient uitsluitend aan het verhogen van de opbrengst per abonnee. Daarmee is de economische functie van het bureau niet de productie maar de conversie. Elk instrument dat de conversie verhoogt — segmentatie, massabericht, tijdgebonden aanbod, een chatter die nooit offline is — is vanuit die positie een investering met directe terugverdientijd. Boek I heeft laten zien dat dat gereedschap bestaat en openlijk wordt verkocht; dit boek laat zien waarom het rendabel is."),
  ("p", "Dat is geen morele vaststelling maar een rekenkundige. Zolang de marge van het bureau op berichten ligt en niet op materiaal, zal het bureau berichten optimaliseren. De vraag die de rest van dit boek stelt, is welke grenzen het betaalsysteem en het recht aan die optimalisatie stellen — en waar die grenzen in de praktijk niet zichtbaar worden gemaakt."),
 ]},

{"num": "02", "part": "DEEL I — DE ROUTE VAN HET GELD",
 "title": "Het bureau als onderneming",
 "deck": "Een beheerbureau is een arbeidsintensief bedrijf met een vaste kostenstructuur: ploegen, software, werving. Wie die structuur uitrekent, ziet waarom bezetting rond de klok economisch dwingend wordt.",
 "blocks": [
  ("p", "De kostenkant van een bureau bestaat uit drie posten. De eerste is arbeid: chatters in ploegendienst, betaald per uur, per bericht of op commissie. De tweede is software: een agency-CRM met een abonnement per account of per zetel. [BR-23] [BR-24] [BR-25] De derde is acquisitie: het werven van creators, en het werven van abonnees via advertenties en promotieaccounts."),
  ("p", "De arbeidskosten zijn laag omdat het werk buiten de dure arbeidsmarkten wordt uitgevoerd. De BBC noteerde lonen onder twee dollar per uur. [BR-06] Rappler documenteerde Filipijnse tarieven per bewerkte foto of video. [BR-19] Nikkei Asia beschreef dezelfde arbeidsmarkt in termen van onzekerheid en verloop. [BR-20] Bij die tarieven is een continue bezetting van een account met drie ploegen per etmaal geen luxe maar de standaardconfiguratie."),
  ("box", "Onbevestigde sectorbron",
   "Er circuleren in de sector kostenmodellen die de bezetting van één account per maand becijferen. [BR-39] Dit dossier neemt die getallen niet over: de bron is een commerciële aanbieder zonder controleerbare methodologie. Wat wél vaststaat, zijn de uurlonen uit de journalistieke bronnen en de abonnementsprijzen op de publieke pagina’s van de CRM-leveranciers."),
  ("h2", "Twee soorten bureaus"),
  ("p", "De term ‘agency’ dekt twee verschillende ondernemingen. De eerste is een dienstverlener die een creator werk uit handen neemt tegen commissie, met een opzegbaar contract en behoud van de accounttoegang bij de creator. De tweede is een exploitant die de accounttoegang, de uitbetalingsgegevens en het gespreksverkeer overneemt. Het juridische verschil zit niet in de naam maar in twee bepalingen: wie houdt de sleutel, en op wiens rekening komt het geld binnen."),
  ("q", "In mijn ogen is het geen agentschap, het is moderne slavernij en pooierschap.",
   "‘Lenny’, creator, in Balkan Insight, 13 november 2025 [BR-22]"),
  ("p", "Gedocumenteerde gevallen laten zien wat er gebeurt als die twee bepalingen bij de exploitant liggen: wachtwoorden worden gewijzigd, uitbetalingen lopen naar rekeningen van derden, accounts worden overgedragen zonder instemming van de persoon wiens gezicht erop staat. [BR-05] [BR-14] [BR-17] [BR-22] Dat zijn geen commerciële geschillen over percentages; het zijn vragen over zeggenschap, en daarmee over de vraag wie in juridische zin de onderneming drijft."),
  ("h2", "Waarom dit voor de abonnee telt"),
  ("p", "Een abonnee heeft geen contract met het bureau en kent zijn bestaan doorgaans niet. Toch bepaalt dat bureau wat hij leest, wanneer hij het leest, welke prijs hem wordt getoond en welke gegevens over hem worden vastgelegd. De partij met de grootste invloed op zijn ervaring is de partij die in geen enkel document voorkomt dat hij ooit onder ogen krijgt. Dat is geen randverschijnsel van de structuur; het is de structuur."),
 ]},

{"num": "03", "part": "DEEL II — HET BETAALSYSTEEM",
 "title": "Hoog risico: hoe het betaalverkeer deze sector behandelt",
 "deck": "Betaaldienstverleners kennen een aparte categorie voor handelaren met verhoogd risico. Die categorie is geen beschuldiging maar een tariefstructuur — en zij verklaart een deel van het gedrag in deze markt.",
 "blocks": [
  ("p", "In het betaalverkeer bestaat een formele categorie handelaren met hoog risico. Die indeling volgt uit terugboekingsratio’s, reputatierisico en toezichtsverwachtingen. Europese toezichtsdocumentatie over witwasrisico bij kaartacquiring en e-geld beschrijft de verplichtingen die daarbij horen: verscherpte cliëntonderzoeksmaatregelen, monitoring van transactiepatronen en het aanhouden van reserves. [BR-44]"),
  ("p", "De praktische gevolgen zijn concreet. Een handelaar in deze categorie betaalt hogere transactiekosten, ziet een deel van zijn omzet maanden in reserve staan en loopt het risico dat zijn overeenkomst wordt opgezegd. Dat maakt de betaaldienstverlener tot de feitelijke poortwachter van de sector: niet de wetgever, niet de toezichthouder, maar de partij die de kaarttransactie accepteert of weigert."),
  ("box", "Definitie",
   "Terugboeking (chargeback): het terugdraaien van een kaartbetaling op verzoek van de kaarthouder, bijvoorbeeld bij een niet-toegestane transactie of een niet-geleverde dienst. Onder PSD2 heeft de betaaldienstgebruiker recht op terugbetaling van niet-toegestane betalingstransacties; de bewijslast dat een transactie wél is geautoriseerd, ligt bij de betaaldienstverlener. [BR-45]"),
  ("h2", "Micro-transacties en zichtbaarheid"),
  ("p", "De opbrengst in deze sector bestaat niet uit één abonnement maar uit een reeks kleine bedragen: berichtinhoud met een prijs, fooien, tijdgebonden aanbiedingen. Voor de abonnee is elke afzonderlijke afschrijving klein genoeg om niet te controleren. Voor de handelaar is dat gunstig: kleine bedragen leiden tot minder betwistingen dan één groot bedrag. Dat is geen vermoeden over opzet, maar een bekende eigenschap van betaalgedrag."),
  ("p", "Het gevolg is een blinde vlek. Financieel toezicht is ingericht op patronen: ongebruikelijk grote bedragen, ongebruikelijke bestemmingen, ongebruikelijke frequentie. Een stroom van kleine, vrijwillige betalingen aan een handelaar met een geldige overeenkomst produceert geen van die signalen. De omvang van de stroom wordt pas zichtbaar in de geaggregeerde jaarcijfers van het platform — en daar is zij niet meer herleidbaar tot individuele gesprekken."),
  ("h2", "Wat dit hoofdstuk niet beweert"),
  ("p", "Het bestaan van een risicocategorie zegt niets over de intenties van individuele partijen. Legitieme ondernemingen vallen erin, en de categorie wordt ook toegepast op sectoren zonder enige verdenking. Dit hoofdstuk stelt uitsluitend vast dat de betaalinfrastructuur deze markt anders behandelt dan gewone detailhandel, en dat die behandeling gevolgen heeft voor kosten, reserves en poortwachterschap."),
 ]},

{"num": "04", "part": "DEEL II — HET BETAALSYSTEEM",
 "title": "Wat een terugboeking onthult",
 "deck": "De terugboeking is het enige moment waarop een abonnee tegenspraak organiseert. Wat er dan gebeurt, legt de zwakte van zijn positie bloot.",
 "blocks": [
  ("p", "Wie betaalde voor gesprekken in de veronderstelling dat hij met een bepaald persoon sprak, en achteraf ontdekt dat een ploeg medewerkers schreef, heeft een civielrechtelijke vraag: heeft hij gekregen waarvoor hij betaalde? Boek V behandelt de juridische kant. Hier gaat het om het betaaltechnische spoor."),
  ("p", "Een terugboeking vereist een grond. ‘De dienst was niet zoals voorgesteld’ is een moeilijke grond wanneer de dienst formeel wordt omschreven als toegang tot berichten en materiaal — niet als contact met een specifiek persoon. De voorwaarden van platformen en bureaus zijn doorgaans zo opgesteld dat het geleverde product neutraal is omschreven. Daarmee verplaatst het geschil zich van ‘is er geleverd?’ naar ‘wat is beloofd?’, en dat is precies de vraag die nergens schriftelijk wordt beantwoord."),
  ("box", "Bewijsgrens",
   "Dit dossier beschikt niet over cijfers over terugboekingsratio’s in deze sector. Er bestaat geen publieke, controleerbare bron die ze rapporteert. De analyse hierboven beschrijft de juridische en praktische structuur van een terugboeking, niet de frequentie ervan."),
  ("h2", "Drie hindernissen voor de gedupeerde"),
  ("ul", ["Bewijs: het gesprek staat op een platform waartoe de gebruiker na opzegging vaak geen toegang meer heeft. Zonder export is de inhoud weg.",
          "Omschrijving: de dienst is contractueel neutraal geformuleerd, waardoor de belofte waarop de koper afging nergens is vastgelegd.",
          "Schaamte: de kosten van het aankaarten zijn voor de betrokkene hoog en persoonlijk; dat onderdrukt het aantal betwistingen stelselmatig."],),
  ("p", "Die derde hindernis is economisch relevant. Een markt waarin het aankaarten van een klacht voor de klager zelf beschamend is, produceert structureel te weinig klachten om als signaal te dienen. Toezicht dat op meldingen steunt, ziet daardoor niet wat er gebeurt. Boek VI werkt dit uit tot een concreet protocol voor gedupeerde kopers, inclusief het veiligstellen van bewijs vóór opzegging."),
 ]},

{"num": "05", "part": "DEEL III — DE RANDMARKTEN",
 "title": "De tweede markt: cursussen, bureaus en de handel in het model zelf",
 "deck": "Rond de sector is een tweede economie ontstaan die niet aan abonnees verdient, maar aan mensen die zelf willen toetreden.",
 "blocks": [
  ("p", "De BBC en The Guardian beschreven in juni 2026 de handel in cursussen en opleidingen voor het opzetten van beheerbureaus. [BR-05] [BR-09] Het patroon is bekend uit andere sectoren: wanneer de marges aan de onderkant dalen, verschuift de winst naar het verkopen van toegang tot het model. De koper betaalt voor een methode; de verkoper verdient ongeacht of die methode werkt."),
  ("p", "Economisch is dat een aparte markt met een eigen risicoprofiel. De klant is hier geen abonnee maar een aspirant-ondernemer. De belofte is geen intimiteit maar rendement. En de informatie-asymmetrie is dezelfde: de verkoper beschikt over de werkelijke slagingskansen, de koper niet."),
  ("h2", "Werving van creators"),
  ("p", "Dezelfde markt kent een wervingskant. Bureaus werven mensen die nog geen account hebben, met beloften over opbrengst en begeleiding. De contracten die daaruit voortkomen zijn beschreven in de bronnen van Boek I: exclusiviteit, lange looptijd, boetebedingen, en in de zwaarste gevallen overdracht van accounttoegang en uitbetalingsgegevens. [BR-05] [BR-14] [BR-22]"),
  ("p", "Onder Europees recht zijn bedingen die het evenwicht tussen partijen aanzienlijk verstoren ten nadele van de consument toetsbaar en potentieel nietig. [BR-46] Waar de creator als consument kwalificeert — en dat is bij particuliere toetreders bepaald niet ondenkbaar — is er dus al een bestaande toetsingsgrond, zonder dat er nieuwe wetgeving nodig is. Boek V werkt die route uit."),
  ("box", "Feit, interpretatie, voorstel",
   "Feit: er bestaat een handel in cursussen en in wervingscontracten, journalistiek gedocumenteerd. Interpretatie: die handel verschuift de winst van de exploitatie naar de toetreding, een bekend patroon bij dalende marges. Voorstel: standaardtoetsing van dergelijke contracten aan de richtlijn oneerlijke bedingen, op initiatief van consumentenautoriteiten — uitgewerkt in Boek V."),
 ]},

{"num": "06", "part": "DEEL III — DE RANDMARKTEN",
 "title": "De bewijsgrens van de schaduweconomie",
 "deck": "Over deze sector circuleren zware beweringen over witwassen en gestolen kaartgegevens. Dit hoofdstuk legt uit waarom dit dossier ze niet overneemt, en welk onderzoek nodig is om ze te beantwoorden.",
 "blocks": [
  ("p", "De bewering luidt dat micro-transacties in deze markt op schaal dienen als afzetkanaal voor gestolen kaartgegevens of als witwaskanaal. Dit dossier merkt die bewering aan als onbevestigd. [CL-27] Er is in dit onderzoek geen enkele opsporings-, toezichts- of rechtbankbron aangetroffen die haar staaft. Het ontbreken van bewijs is geen weerlegging, maar het is evenmin een vrijbrief om de bewering te herhalen."),
  ("box", "Waarom deze terughoudendheid",
   "Een dossier dat op één punt speculeert, verliest zijn waarde op alle andere punten. De vaststellingen in Boek I en Boek V zijn hard en controleerbaar. Ze zouden door één onbewezen beschuldiging over financiële criminaliteit ontkracht kunnen worden in elke procedure waarin dit dossier wordt ingebracht."),
  ("h2", "Wat wél vaststaat"),
  ("ul", ["Deze markt valt in het betaalverkeer onder de categorie hoog risico, met bijbehorende monitoring- en reserveverplichtingen. [BR-44]",
          "De opbrengst bestaat uit grote aantallen kleine transacties, wat de zichtbaarheid per transactie verlaagt.",
          "Uitbetalingen lopen in gedocumenteerde gevallen naar rekeningen van derden in plaats van naar de persoon op het account. [BR-05] [BR-22]",
          "De keten is grensoverschrijdend: platform, bureau, chatters en betaaldienstverlener bevinden zich vaak in verschillende rechtsgebieden."]),
  ("p", "Die vier vaststellingen rechtvaardigen een onderzoeksvraag, geen conclusie. De vraag luidt: in hoeverre maakt de combinatie van hoge transactievolumes, lage bedragen per transactie en uitbetaling aan derden het toezicht op deze keten feitelijk onmogelijk?"),
  ("h2", "Welk onderzoek de vraag zou beantwoorden"),
  ("ul", ["Een steekproef van acquiringdossiers in deze sector door een toezichthouder, gericht op uiteindelijk begunstigden van uitbetalingen.",
          "Aggregatie van terugboekingsratio’s per handelaarscategorie, geanonimiseerd gepubliceerd.",
          "Koppeling van bureau-inschrijvingen aan de rekeningen waarop platformuitbetalingen binnenkomen.",
          "Een vergelijkend onderzoek in twee lidstaten naar de vraag of een creator die zijn accounttoegang kwijt is, ergens terechtkan."]),
  ("p", "Zolang dat onderzoek niet is gedaan, blijft dit hoofdstuk staan waar het staat: bij de vraag. Dat is geen zwakte van het dossier maar de reden dat de rest ervan overeind blijft."),
 ]},
]
