# -*- coding: utf-8 -*-
"""Aanvullende hoofdstukken per boek.

Deze hoofdstukken verdiepen de bestaande analyse met casuïstiek, citaten en
toetsbare voorstellen. Ze worden vóór het slothoofdstuk van elk deel ingevoegd.
"""

EXPANSIONS = {

"I": [
{"part": "DEEL II — DE MACHINERIE",
 "title": "De ploegendienst: één persoon, drie schrijvers, vierentwintig uur",
 "deck": "Continuïteit is het moeilijkste onderdeel van uitbestede intimiteit. Dit hoofdstuk beschrijft hoe zij technisch en organisatorisch wordt geproduceerd.",
 "blocks": [
  ("p", "Een gesprek dat dag en nacht doorloopt, kan niet door één mens worden gevoerd. De oplossing is de ploegendienst: het account wordt bemand in blokken, met overdracht aan het einde van elke dienst. De BBC beschreef diensten van acht uur, vijf dagen per week. [BR-06] De chatter logt in op een dashboard, ziet de gesprekken die aan haar zijn toegewezen en neemt over waar de vorige stopte."),
  ("p", "Wat die overdracht mogelijk maakt, is niet geheugen maar administratie. De notitievelden in het CRM bevatten wat de vorige schrijver heeft vastgelegd: de naam van de hond, de scheiding, de nachtdienst van de abonnee, de laatste aankoop en het bedrag. [BR-23] [BR-24] De illusie van herinnering wordt geproduceerd door een database die precies daarvoor is ontworpen."),
  ("q", "We keyboard smash, intentionally misspell, and use Gen Z slang.",
   "Filipijnse chatter, in Rest of World, 20 augustus 2025 [BR-21]"),
  ("h2", "Drie technische vereisten"),
  ("ul", ["Eén toonregister: schrijfstijl, emoji-gebruik en aanspreekvorm worden per account vastgelegd zodat wisselingen niet opvallen.",
          "Eén feitenbasis: alles wat over de abonnee bekend is, staat in gedeelde velden en niet in iemands hoofd.",
          "Eén verkoopstaat: waar in het traject de abonnee zich bevindt — kennismaking, binding, aanbod — bepaalt welk script geldt."]),
  ("p", "Die drie vereisten zijn precies de functies die de agency-software aanbiedt. De software is dus geen hulpmiddel bij het gesprek; zij is de voorwaarde waaronder het gesprek door wisselende personen gevoerd kan worden zonder dat de lezer het merkt."),
  ("box", "Bewijsgrens",
   "De organisatie van ploegen en overdracht is beschreven door chatters in vier onafhankelijke publicaties en komt overeen met de functiebeschrijvingen van de leveranciers. Hoeveel accounts op deze wijze worden bemand, is niet vastgesteld."),
 ]},
{"part": "DEEL II — DE MACHINERIE",
 "title": "De automatisering: waar de mens ophoudt en het model begint",
 "deck": "Tussen volledig menselijk en volledig geautomatiseerd ligt het grootste deel van de praktijk: een model dat voorstelt, een mens die goedkeurt.",
 "blocks": [
  ("p", "Reuters beschreef software die antwoorden genereert of suggereert in gesprekken die als persoonlijk worden gepresenteerd. [BR-02] Leveranciers adverteren er zelf mee. [BR-24] [BR-25] De gangbare configuratie is niet de volledig autonome bot maar de suggestie: het model stelt een antwoord voor, de chatter past het aan of verstuurt het ongewijzigd."),
  ("p", "Die tussenvorm is juridisch de lastigste. Artikel 50 van de AI-verordening verplicht vanaf 2 augustus 2026 tot de mededeling dat een gebruiker met een AI-systeem interageert. [BR-34] Maar interageert de abonnee met een AI-systeem wanneer een mens op verzenden drukt? Boek V behandelt die vraag; hier volstaat de vaststelling dat de ontwerpkeuze — mens in de lus — precies op de grens van de meldplicht ligt."),
  ("box", "Feit, interpretatie, voorstel",
   "Feit: AI genereert of suggereert antwoorden in als persoonlijk gepresenteerde gesprekken [CL-08]. Interpretatie: de configuratie met een mens in de lus ligt op de grens van de meldplicht uit artikel 50. Voorstel: laat de mededelingsplicht aangrijpen op de vraag wie de tekst opstelt, niet op de vraag wie hem verzendt."),
  ("h2", "Wat automatisering economisch doet"),
  ("p", "Automatisering verlaagt de kosten per bericht en verhoogt daarmee het optimale aantal berichten. Waar een chatter tien gesprekken tegelijk kan voeren, voert zij er met suggesties dertig. Rest of World documenteerde de keerzijde voor de arbeidsmarkt: Filipijnse chatters zien hun werk verdwijnen naar modellen die hun toon hebben geleerd. [BR-21]"),
  ("p", "De abonnee merkt van die verschuiving niets, en dat is het punt. Zijn ervaring blijft gelijk terwijl de productiewijze erachter fundamenteel verandert. Geen enkel signaal in het product markeert dat verschil."),
 ]},
],

"II": [
{"part": "DEEL II — HET BETAALSYSTEEM",
 "title": "Prijszetting: wat een bericht kost en waarom",
 "deck": "De prijs van een bericht is geen vaste prijs. Zij wordt per ontvanger bepaald, op basis van wat het systeem over hem weet.",
 "blocks": [
  ("p", "In de agency-software is prijsdifferentiatie een functie: segmenten krijgen verschillende aanbiedingen, en de prijs van afzonderlijke berichtinhoud wordt per gesprek gezet. [BR-23] [BR-24] [BR-25] Wat in de detailhandel een gevoelig onderwerp zou zijn — verschillende prijzen voor hetzelfde product op basis van betalingsbereidheid — is hier de standaardwerkwijze."),
  ("p", "Het verschil met dynamische prijzen in andere sectoren is de informatiebron. Een luchtvaartmaatschappij differentieert op boekingsmoment; hier gebeurt het op wat iemand over zijn leven heeft verteld in een gesprek dat hij als privé beschouwde. Dat verschil is niet gradueel maar principieel."),
  ("box", "Bewijsgrens",
   "Dat segmentatie op bestedingsvermogen bestaat, staat vast op grond van de publieke productpagina’s [CL-02]. Dat prijsverschillen doelbewust worden gekoppeld aan psychische kwetsbaarheid, is niet aangetoond en staat als onbevestigd geregistreerd [CL-14]."),
  ("h2", "De drie prijsvormen"),
  ("table", [["Vorm", "Wat de koper ziet", "Wat het systeem stuurt"],
             ["Abonnement", "Vaste maandprijs", "Instapkorting, verlengingsaanbod, retentiereeks"],
             ["Betaalde berichtinhoud", "Prijs per bericht", "Prijs per segment, tijdgebonden vervaldatum"],
             ["Fooi", "Vrijwillige gift", "Aangespoord via gespreksmoment en schaarste"]],
   [22, 34, 44]),
  ("p", "De derde vorm is de interessantste, omdat zij formeel volledig vrijwillig is en dus buiten vrijwel elke consumentenrechtelijke bescherming valt. Een gift kent geen product, dus ook geen gebrek, dus ook geen ontbinding."),
 ]},
{"part": "DEEL III — DE RANDMARKTEN",
 "title": "Casus: 178.000 bruto, 10.000 netto",
 "deck": "Eén gedocumenteerde zaak, uitgerekend tot op de schakel. Geen anoniem verhaal maar een gepubliceerd geval.",
 "blocks": [
  ("p", "Balkan Insight documenteerde in november 2025 het geval van een creator die op een bruto-opbrengst van 178.000 dollar zelf ongeveer 10.000 dollar ontving. [BR-22] Die verhouding — ongeveer zes procent — is geen gemiddelde en wordt hier ook niet als zodanig gepresenteerd. Zij is een gedocumenteerd uiterste dat laat zien wat de contractstructuur in de praktijk kan opleveren."),
  ("q", "In mijn ogen is het geen agentschap, het is moderne slavernij en pooierschap.",
   "‘Lenny’, creator, in Balkan Insight, 13 november 2025 [BR-22]"),
  ("h2", "De rekening ontleed"),
  ("ul", ["Platforminhouding: twintig procent van het bruto, contractueel vastgelegd en kenbaar.",
          "Bureaucommissie: de grootste post, in gedocumenteerde contracten de helft tot twee derde. [BR-05] [BR-14]",
          "Kosten die worden doorbelast: promotie, beeldbewerking, chattersinzet — posten waarvan de creator de hoogte niet kan verifiëren.",
          "Wat resteert: het bedrag dat de persoon op het account daadwerkelijk ontvangt."]),
  ("p", "De derde post is de kern van het probleem. Waar commissie een percentage is dat te controleren valt, zijn doorbelaste kosten een open categorie die alleen de andere partij kan narekenen. In een verhouding waarin die partij ook de accounttoegang en de uitbetalingsrekening beheert, bestaat er feitelijk geen controle."),
  ("box", "Feit, interpretatie, voorstel",
   "Feit: in een gedocumenteerd geval bleef zes procent van de bruto-opbrengst bij de creator. Interpretatie: niet-verifieerbare doorbelasting maakt de werkelijke verdeling oncontroleerbaar. Voorstel: verplichte, gespecificeerde afrekening per periode, met platformuitbetaling uitsluitend op rekening van de accounthouder."),
 ]},
{"part": "DEEL III — DE RANDMARKTEN",
 "title": "Wat toezichthouders nu al kunnen opvragen",
 "deck": "Geen nieuwe bevoegdheden nodig: vier documenten volstaan om de keten van één account in kaart te brengen.",
 "blocks": [
  ("ul", ["Het beheercontract tussen creator en bureau, inclusief bijlagen over commissie en kosten.",
          "Het uitbetalingsoverzicht van het platform: op welke rekening en op welke naam.",
          "De licentieovereenkomst met de CRM-leverancier: welke functies zijn afgenomen en wie heeft toegang.",
          "De verwerkersovereenkomst: wie is verwerkingsverantwoordelijke voor de abonneedossiers. [BR-32]"]),
  ("p", "Die vier documenten bestaan in elke professionele opzet en zijn met bestaande bevoegdheden opvraagbaar. Samen beantwoorden zij de vraag die dit hele dossier stelt: wie voert feitelijk de onderneming, en wie is dus de handelaar tegenover de consument."),
  ("box", "Waarom dit geen nieuwe wet vergt",
   "Consumentenautoriteiten kunnen bij een onderzoek naar een mogelijk misleidende handelspraktijk bedrijfsdocumentatie vorderen. Gegevensbeschermingsautoriteiten kunnen verwerkersovereenkomsten opvragen. Beide bevoegdheden bestaan en worden in andere sectoren routinematig gebruikt."),
  ("p", "De conclusie van Boek II is daarmee niet dat de geldstroom ondoorgrondelijk is, maar dat zij ondoorgrond blijft. Dat is een verschil van beleid, niet van mogelijkheid."),
 ]},
],

"III": [
{"part": "DEEL I — HET SCHEMA",
 "title": "Timing als instrument",
 "deck": "Wanneer een bericht aankomt, doet meer met de lezer dan wat erin staat. Dit hoofdstuk behandelt de dag, het uur en de stilte.",
 "blocks": [
  ("p", "Verzendplanning is in de agency-software een basisfunctie: berichten worden op gekozen momenten uitgestuurd, per segment. [BR-23] [BR-24] Wat dat psychologisch doet, is bekend: een bericht dat aankomt op een moment van alleen-zijn wordt anders gelezen dan hetzelfde bericht overdag."),
  ("p", "De stilte werkt in dezelfde richting. Een uitblijvend antwoord verhoogt het controlegedrag en daarmee het aantal keren dat de app wordt geopend. Chatters beschrijven het bewust laten wachten als techniek. [BR-07] Ook hier geldt: het is niet de inhoud die stuurt, maar het ritme."),
  ("box", "Bewijsgrens",
   "Dat verzendmomenten worden gepland, staat in de productdocumentatie. Dat die planning doelbewust op kwetsbare uren is afgestemd, is in dit dossier niet aangetoond en wordt niet beweerd."),
  ("h2", "Waarom dit voor regulering uitmaakt"),
  ("p", "In andere sectoren is timing al een reguleringsobject: er gelden beperkingen op gokreclame rond bepaalde tijdstippen en op pushmeldingen bij bepaalde diensten. Het principe is aanvaard. Het is nooit toegepast op betaald persoonlijk contact, omdat die categorie in het toezicht simpelweg niet bestaat."),
 ]},
{"part": "DEEL II — DE BETROKKENEN",
 "title": "Het dossier over de lezer",
 "deck": "Wat er over een abonnee wordt vastgelegd, bepaalt wat hij te lezen krijgt. Dit hoofdstuk beschrijft die terugkoppeling.",
 "blocks": [
  ("p", "Boek I stelde vast dat notitievelden bestaan en gebruikt worden: relatiestatus, verlies, koopgedrag. [CL-09] Het psychologische effect van die dossiervorming ligt niet in de opslag maar in de terugkoppeling: wat iemand vertelt, komt later terug als blijk van aandacht. Herinnerd worden is een van de sterkste sociale beloningen die er bestaan."),
  ("p", "Wanneer die herinnering uit een database komt en dient om de volgende aankoop te sturen, is de beloning echt en de oorsprong niet. De lezer ervaart erkenning; het systeem registreert een conversiestap. Dat is de kern van wat dit dossier deceptie noemt, uitgedrukt in psychologische termen."),
  ("box", "Definitie",
   "Terugkoppeling: het opnieuw aanbieden van eerder verstrekte persoonlijke informatie als teken van betrokkenheid. In een CRM-omgeving is dat een functie; in een relatie is het een deugd. Het verschil is voor de ontvanger niet waarneembaar."),
  ("h2", "Gevolg voor de bewijsvoering"),
  ("p", "Wie later wil aantonen dat hij is misleid, heeft aan de inhoud van de gesprekken weinig: die is per definitie warm en persoonlijk. Het bewijs zit in de administratie erachter — de segmenten, de notities, de scripts. Boek VI beschrijft daarom het inzageverzoek als eerste instrument voor gedupeerden, en niet het gespreksverslag."),
 ]},
],

"IV": [
{"part": "DEEL II — HET SCENARIO",
 "title": "Wat statistiek niet kan zeggen",
 "deck": "Een methodologisch hoofdstuk, omdat de meeste fouten in dit domein geen fouten in de cijfers zijn maar in de redenering erover.",
 "blocks": [
  ("h3", "Ecologische drogreden"),
  ("p", "Uit een landencijfer volgt niets over een individu. Dat Korea een vruchtbaarheidscijfer van 0,75 registreert [BR-40], zegt niets over de keuzes van enige specifieke Koreaan, en al helemaal niets over de oorzaak daarvan."),
  ("h3", "Gelijktijdigheid is geen oorzaak"),
  ("p", "Twee dalende of stijgende reeksen in dezelfde periode zijn een uitgangspunt voor onderzoek, geen bevinding. In een tijdvak waarin vrijwel alle sociale en technologische reeksen bewegen, is samenloop de regel."),
  ("h3", "Ontbrekende variabelen"),
  ("p", "Woonlasten, arbeidsmarkt, opleidingsduur en migratie beïnvloeden zowel het digitale gedrag als de demografie. Zonder die variabelen in het model is elk verband dat overblijft onbruikbaar."),
  ("h3", "Selectie"),
  ("p", "Wie zijn steekproef trekt onder gebruikers van een dienst, meet de eigenschappen van gebruikers, niet het effect van de dienst."),
  ("box", "Waarom dit hoofdstuk in het dossier staat",
   "Omdat de bewering die dit dossier níét doet — dat deze bedrijfstak geboortecijfers beïnvloedt — de meest voorspelbare misvatting is bij het lezen van Boek IV. Het hoofdstuk staat er om die lezing onmogelijk te maken."),
 ]},
{"part": "DEEL III — DE SAMENLEVING",
 "title": "De meetagenda",
 "deck": "Concrete, uitvoerbare metingen die de openstaande vraag zouden kunnen beantwoorden, met vermelding van wie ze kan uitvoeren.",
 "blocks": [
  ("table", [["Meting", "Instrument", "Uitvoerder"],
             ["Tijd besteed aan betaald digitaal contact", "Tijdsbestedingsonderzoek, extra categorie", "Nationale statistiekbureaus [BR-43]"],
             ["Uitgaven per huishoudtype", "Budgetonderzoek, aparte bestedingscode", "Nationale statistiekbureaus"],
             ["Aanvulling of vervanging", "Panelvragenlijst, longitudinaal", "Universitair onderzoek"],
             ["Segmentatiepraktijk", "Inzagedossiers en verwerkersovereenkomsten", "Gegevensbeschermingsautoriteiten [BR-32]"],
             ["Ketenstructuur", "Acquiring- en uitbetalingsdossiers", "Financieel toezicht [BR-44]"]],
   [32, 38, 30]),
  ("p", "Vier van de vijf metingen vergen geen nieuwe bevoegdheid en geen nieuw instrument; zij vergen een extra categorie in bestaand onderzoek. Dat is de goedkoopste vorm van kennis die in dit dossier wordt voorgesteld."),
  ("box", "Feit, interpretatie, voorstel",
   "Feit: er bestaat geen meting van substitutie tussen betaald digitaal contact en onbetaald contact. Interpretatie: die leemte maakt elk maatschappelijk debat hierover ongefundeerd. Voorstel: neem de categorie op in bestaand tijdsbestedings- en budgetonderzoek."),
 ]},
],

"V": [
{"part": "DEEL III — HANDHAVING",
 "title": "De procedure die een gedupeerde werkelijk kan voeren",
 "deck": "Van klacht tot vonnis: welke route bestaat er vandaag, en waar loopt zij vast?",
 "blocks": [
  ("h3", "Route 1 — Consumentenautoriteit"),
  ("p", "Een melding wegens misleidende omissie onder artikel 7 UCPD. [BR-31] Voordeel: geen kosten, geen procesrisico. Nadeel: de autoriteit beslist zelf of zij optreedt, en handhaaft doorgaans pas bij een patroon van meldingen."),
  ("h3", "Route 2 — Gegevensbeschermingsautoriteit"),
  ("p", "Een klacht over de verwerking van bijzondere persoonsgegevens en over het ontbreken van de informatieplicht. [BR-32] Voordeel: de bewijslast voor rechtmatige verwerking ligt bij de verwerkingsverantwoordelijke. Nadeel: de procedure duurt lang en levert de betrokkene zelden geld op."),
  ("h3", "Route 3 — Civiele vordering"),
  ("p", "Een vordering tot vernietiging wegens dwaling of tot schadevergoeding. Voordeel: rechtstreeks resultaat. Nadeel: bewijslast, kosten en het publieke karakter van de procedure — voor veel gedupeerden een onoverkomelijke drempel."),
  ("h3", "Route 4 — Collectieve actie"),
  ("p", "In de Verenigde Staten lopen twee collectieve procedures tegen het platform en acht bureaus. [BR-03] [BR-04] In de EU maakt de richtlijn representatieve vorderingen mogelijk voor consumentenorganisaties. Dat is de enige route die de schaamtedrempel omzeilt, omdat de individuele gedupeerde anoniem blijft."),
  ("box", "Conclusie van dit hoofdstuk",
   "Route 4 is de enige die past bij de structuur van dit probleem: veel gedupeerden, kleine bedragen, hoge persoonlijke kosten van melden. Elke maatregel die de collectieve route versterkt, doet meer dan tien individuele vonnissen."),
 ]},
{"part": "DEEL III — HANDHAVING",
 "title": "Het modelvoorstel, artikelsgewijs",
 "deck": "Lex Humanitas Digitalis in vijf bepalingen, met per bepaling de bestaande norm waarop zij aansluit. Voorstel, geen geldend recht.",
 "blocks": [
  ("box", "Status van deze tekst",
   "Wat hierna volgt is een modelvoorstel van de auteur. Het is geen geldend recht, geen aanhangig wetsvoorstel en geen weergave van een bestaand initiatief. Het is geschreven om bekritiseerd en verbeterd te worden."),
  ("h3", "Artikel 1 — Mededeling van auteurschap"),
  ("p", "Vóór de eerste betaalde uitwisseling deelt de aanbieder mee of berichten worden opgesteld door de genoemde persoon, door een gemachtigde derde, of door een geautomatiseerd systeem. Sluit aan op: art. 7 UCPD [BR-31] en art. 50 AI-verordening [BR-34]."),
  ("h3", "Artikel 2 — Waarheidsplicht bij directe vraag"),
  ("p", "Een onjuist antwoord op de vraag wie schrijft, geldt als misleidende handeling. Sluit aan op: art. 6 UCPD [BR-31]."),
  ("h3", "Artikel 3 — Verbod op exploitatie van intiem prijsgegeven gegevens"),
  ("p", "Gegevens over gezondheid, rouw, verslaving of financiële nood die in een als persoonlijk gepresenteerd gesprek zijn prijsgegeven, mogen niet worden gebruikt voor segmentatie, prijszetting of verkoopsturing. Sluit aan op: art. 9 AVG [BR-32] en art. 26 lid 3 DSA [BR-33]."),
  ("h3", "Artikel 4 — Nietigheid van ontzeggingsbedingen"),
  ("p", "Bedingen die de accounthouder permanente toegang tot eigen account, inkomsten, publiek of gegevens ontzeggen, zijn nietig. Sluit aan op: richtlijn 93/13/EEG [BR-46] en art. 20 AVG [BR-32]."),
  ("h3", "Artikel 5 — Ketenaansprakelijkheid en registratie"),
  ("p", "Platformen registreren door derden beheerde accounts en publiceren geaggregeerde cijfers; de partij die de gespreksvoering organiseert is medeaansprakelijk voor overtreding van artikel 1 tot en met 3. Sluit aan op: art. 34–35 DSA [BR-33]."),
  ("box", "Wat dit voorstel niet doet",
   "Het verbiedt geen ondersteuning, geen ghostwriting, geen fictie en geen enkele vorm van sekswerk. Het verplicht uitsluitend tot mededeling van auteurschap tegenover de betalende partij, en beschermt gegevens die in vertrouwen zijn prijsgegeven."),
 ]},
],

"VI": [
{"part": "DEEL I — PROTOCOLLEN",
 "title": "Protocol voor redacties en onderzoekers",
 "deck": "Wie dit onderwerp onderzoekt, loopt tegen dezelfde muren aan. Dit hoofdstuk deelt wat in dit dossier werkte.",
 "blocks": [
  ("ul", ["Begin bij de leverancier, niet bij het slachtoffer: productpagina’s van CRM-aanbieders beschrijven de praktijk in hun eigen woorden en zijn citeerbaar. [BR-23] [BR-24] [BR-25]",
          "Werk met jaarrekeningen: de financiële omvang is publiek en controleerbaar. [BR-35] [BR-36]",
          "Verzamel processtukken: class actions en vonnissen leveren gedocumenteerde feiten die niet op anonieme bronnen rusten. [BR-03] [BR-04] [BR-38]",
          "Registreer elke bewering met een status. Zonder claimregister is een dossier over misleiding zelf niet toetsbaar."]),
  ("p", "De vier undercoververslagen waarop dit dossier steunt, zijn het kostbaarste materiaal in het veld. [BR-07] [BR-15] [BR-16] [BR-06] Zij zijn ook het moeilijkst te herhalen: bureaus screenen scherper sinds de publicaties. Dat maakt documentanalyse — contracten, software, jaarcijfers — de meest houdbare onderzoekslijn."),
  ("box", "Bewijsgrens",
   "Dit protocol is een weergave van de werkwijze van dit dossier, geen methodologische standaard. De beperkingen ervan, waaronder het ontbreken van wederhoor, staan in het methodologiehoofdstuk."),
 ]},
{"part": "DEEL II — HERSTEL",
 "title": "Wat een platform morgen kan doen",
 "deck": "Zonder wetswijziging, zonder rechter: vijf productbeslissingen die binnen één ontwikkelcyclus haalbaar zijn.",
 "blocks": [
  ("ul", ["Toon per gesprek of het account door derden wordt beheerd. De registratie bestaat al intern; alleen de weergave ontbreekt.",
          "Geef abonnees een uitgavenoverzicht per maand en de mogelijkheid een plafond in te stellen.",
          "Maak gespreksgeschiedenis exporteerbaar en na opzegging nog twaalf maanden toegankelijk.",
          "Beperk het aantal betaalde aanbiedingen per gesprek per dag.",
          "Geef de accounthouder een niet-overdraagbaar herstelkanaal voor haar eigen account."]),
  ("p", "Alle vijf zijn productbeslissingen, geen juridische. De DSA verplicht bovendien al tot het beoordelen en beperken van systeemrisico’s die uit het ontwerp voortvloeien. [BR-33] Een platform dat deze vijf invoert, verkleint aantoonbaar het risico dat het zelf moet beoordelen."),
  ("box", "Feit, interpretatie, voorstel",
   "Feit: platformen registreren intern welke accounts door derden worden beheerd. Interpretatie: het niet tonen daarvan is een ontwerpkeuze, geen technische beperking. Voorstel: weergave in de interface, vóórdat een betaling wordt gedaan."),
 ]},
],
}
