# -*- coding: utf-8 -*-
"""Hoofdstukken van de integrale editie.

Blokgrammatica:
  ("lead", tekst)              inleidende cursieve alinea
  ("h2", tekst)                tussenkop
  ("h3", tekst)                klein kapitaal-label
  ("p", tekst)                 uitgevulde broodtekst
  ("q", citaat, herkomst)      letterlijk citaat met bronregel
  ("ul", [regels])             opsomming
  ("box", titel, tekst)        kaderstuk (bewijsgrens, definitie, methode)
  ("table", [rijen], [breedtes-in-delen])
Bronverwijzingen staan in de tekst als [BR-xx]; de zetter maakt er kleinkapitaal van.
"""

CHAPTERS = [

{"num": "01", "part": "DEEL I — DE MARKT",
 "title": "De omvang van de markt achter het profiel",
 "deck": "Voor je over misleiding kunt spreken, moet je weten hoe groot en hoe scheef de economie is waarin zij plaatsvindt. De cijfers komen uit de jaarrekening van het moederbedrijf, niet uit schattingen.",
 "blocks": [
  ("p", "Fenix International Ltd., de vennootschap achter OnlyFans, verwerkte in boekjaar 2024 7,22 miljard dollar aan betalingen van fans, een stijging van negen procent. De netto-omzet van het bedrijf zelf — het deel dat niet aan creators wordt doorbetaald — bedroeg 1,41 miljard dollar, met een winst voor belasting van 684 miljoen dollar. Het platform telde 4,634 miljoen creator-accounts en 377,5 miljoen fan-accounts. Eigenaar Leonid Radvinsky ontving over dat jaar 497 miljoen dollar aan dividend. [BR-35] [BR-37]"),
  ("p", "Die cijfers zijn geen achtergrondinformatie; zij zijn de eerste feitelijke vaststelling van dit dossier. Een bedrijf met 1,41 miljard dollar netto-omzet en 684 miljoen winst opereert met minder dan vijftienhonderd werknemers. De arbeid die de omzet voortbrengt — het maken van beelden, het voeren van gesprekken, het onderhouden van relaties met honderden miljoenen accounts — vindt buiten de vennootschap plaats, bij creators en bij de dienstverleners die zij inhuren of die hen inhuren."),
  ("h2", "De scheefheid is het bedrijfsmodel, niet een bijwerking"),
  ("p", "In 2023 keerde het platform 5,3 miljard dollar uit aan 4,12 miljoen creator-accounts. [BR-36] Dat is een gemiddelde van ongeveer 1.300 dollar per account per jaar. Een gemiddelde zegt hier weinig: de verdeling is extreem scheef. De inkomsten concentreren zich bij een kleine kopgroep die zoveel berichten ontvangt dat individuele beantwoording fysiek onmogelijk wordt. Precies op dat punt ontstaat de markt voor uitbesteed gesprek."),
  ("p", "Dat is het scharnier van dit dossier. De chat-industrie is geen parasiet op het platform maar een logisch gevolg van zijn ontwerp: het platform verkoopt directe, persoonlijke toegang tot een individu, en beloont vervolgens precies die accounts die zoveel schaal bereiken dat directheid niet langer haalbaar is. De belofte en de bedrijfseconomie wijzen in tegengestelde richting."),
  ("box", "Wat hier is vastgesteld en wat niet",
   "Vastgesteld: de omzet-, account- en dividendcijfers komen uit gedeponeerde jaarrekeningen zoals gerapporteerd door Variety en The Guardian. Niet vastgesteld: welk aandeel van de omzet via uitbestede gesprekken tot stand komt. Er bestaat geen publieke meting van die verhouding; iedere schatting in omloop is afkomstig van marktpartijen met een belang."),
  ("h2", "Drie lagen tussen abonnee en ontvanger"),
  ("p", "Een betaling van een abonnee passeert doorgaans drie lagen voordat zij ergens tot inkomen wordt. Het platform houdt twintig procent in. Daarna volgt, indien aanwezig, het beheerbureau, dat volgens de BBC gemiddeld de helft neemt [BR-05] en volgens Duits onderzoek in sommige contracten tot twee derde [BR-14]. Wat resteert gaat naar de creator, die daaruit soms zelf nog editors of chatters betaalt. Een creator in het onderzoek van Balkan Insight bracht 178.000 dollar bruto op en ontving daarvan 10.000 dollar. [BR-22]"),
  ("q", "In mijn ogen is het geen agentschap, het is moderne slavernij en pooierschap.",
   "‘Lenny’, creator, in Balkan Insight, 13 november 2025 [BR-22]"),
  ("p", "Die verhouding maakt duidelijk waarom het gesprek zelf geïndustrialiseerd wordt. Wanneer een bureau de helft of meer van de opbrengst ontvangt, is zijn verdienmodel niet het maken van beeldmateriaal maar het maximaliseren van de opbrengst per abonnee. Het enige instrument daarvoor is het gesprek: het aantal berichten, de timing, de verkoopmomenten. Het bureau verkoopt geen content. Het verkoopt gespreksvoering."),
  ("h2", "De markt voor gereedschap"),
  ("p", "Rond die gespreksvoering is een softwaremarkt ontstaan die zichzelf openlijk aanprijst. Infloww stelt vijfduizend agentschappen te bedienen. [BR-23] Supercreator claimt 25.000 creators en meer dan 180 miljoen dollar aan gezamenlijk gegenereerd inkomen. [BR-24] OnlyMonster meldt 1.800 bedrijven in meer dan honderd landen. [BR-25] Deze bedrijven adverteren niet richting abonnees. Zij adverteren richting bureaus, en hun verkoopteksten beschrijven onbeschroomd wat het gereedschap doet — hoofdstuk 4 citeert die teksten woordelijk."),
  ("p", "Het punt is niet dat deze software bestaat. Het punt is dat er twee markten zijn met tegengestelde informatie. In de ene markt wordt schaalbare, gesegmenteerde, deels geautomatiseerde gespreksvoering als product verkocht. In de andere markt wordt aan de abonnee een individuele relatie verkocht. Tussen die twee markten staat geen enkele verplichte mededeling."),
 ]},

{"num": "02", "part": "DEEL I — DE MARKT",
 "title": "Wie typt er werkelijk",
 "deck": "Vier journalisten lieten zich als chatter aannemen en publiceerden wat zij binnen kregen: het trainingsmateriaal, de tarieven, de ploegendiensten en de instructies. Dit hoofdstuk is opgebouwd uit dat materiaal.",
 "blocks": [
  ("p", "Op 30 juli 2024 publiceerde Reuters een onderzoek dat de bewijspositie van dit onderwerp veranderde. Het bureau documenteerde dat toppagina’s chatters inhuren om zich als de creator voor te doen en abonnees tot aankopen te bewegen. [BR-01] Waar eerdere berichtgeving berustte op anonieme verhalen, legde Reuters de praktijk vast bij benoemde partijen en koppelde die aan de software die het mogelijk maakt. [BR-02]"),
  ("q", "Many top porn stars on OnlyFans hire ‘chatters’ to impersonate them online and entice subscribers into splurging on explicit content.",
   "Reuters, special report, 30 juli 2024 [BR-01]"),
  ("p", "Het onderzoek bevat het verhaal van Patrick Kunz, een abonnee die tijdens een gesprek vroeg wie hij aan de andere kant had. Het antwoord kwam in de toon die hij gewend was: ‘What do you meann, babyyy? It’s meee!’ Zijn eigen conclusie achteraf is de kern van het hele probleem: ‘I fell for her, but I’m not stupid.’ [BR-01] De abonnee wordt niet dom gehouden door een gebrek aan intelligentie, maar door een gebrek aan informatie die hij redelijkerwijs niet zelf kan verzamelen."),
  ("h2", "De werkvloer"),
  ("p", "WIRED-journalist Brendan Koerner solliciteerde in 2024 als chatter en publiceerde zijn ervaring onder de kop ‘Your online influencer girlfriend is actually a rotating cast of low-wage workers. I became one of them.’ [BR-07] SRF-journaliste Ilona Stämpfli deed hetzelfde bij een Canadees bureau en bracht het trainingsmateriaal naar buiten. [BR-16] De Duitse kunstenares Ella Fleck liet zich onder een mannelijk pseudoniem opleiden en beschreef de aangeleerde techniek als het voeren van de teugels van een paard. [BR-15]"),
  ("q", "Schau, dass der Fan spitz bleibt, damit er möglichst viel Content kauft.",
   "Instructie uit het trainingsmateriaal van een chatter-agentschap, vastgelegd door SRF DOK, 16 januari 2024 [BR-16]"),
  ("p", "De BBC sprak in maart 2026 met mensen die het werk deden. Zij beschreven diensten van acht uur, vijf dagen per week, voor minder dan twee dollar per uur; een latere aanstelling leverde nog steeds minder dan vier dollar per uur op. [BR-06] Rappler documenteerde in februari 2026 de Filipijnse zijde van dezelfde keten: editors en chatters die per bewerkte foto of video tussen 300 en 3.000 peso ontvangen, met meldingen van intimidatie en zonder arbeidsrechtelijke bescherming. [BR-19] Nikkei Asia beschreef dezelfde groep in termen van baanonzekerheid en psychische belasting. [BR-20]"),
  ("q", "It’s kind of icky when you think about it, because you’ll have to do sexting a lot of times.",
   "Chatter, in BBC News, 11 maart 2026 [BR-06]"),
  ("h2", "De structuur van het beroep"),
  ("ul", ["Eén chatter bedient meerdere accounts tegelijk via een centraal dashboard; het account is een werkstation, geen persoon.",
          "De beloning is deels of geheel variabel en gekoppeld aan de omzet uit de toegewezen gesprekken.",
          "Er is ploegenoverdracht: het gesprek loopt door terwijl de schrijver wisselt. Continuïteit wordt bewaakt via notities, niet via geheugen.",
          "Taal en toon worden gestandaardiseerd zodat wisselingen onzichtbaar blijven; chatters melden bewuste tikfouten en straattaal als camouflage. [BR-21]"]),
  ("q", "We keyboard smash, intentionally misspell, and use Gen Z slang. I don’t think AI is at that level of flirting yet.",
   "Filipijnse chatter, in Rest of World, 20 augustus 2025 [BR-21]"),
  ("p", "Dat laatste citaat verdient aandacht, want het draait de gebruikelijke intuïtie om. De onvolmaaktheid van het bericht — de tikfout, het slordige hoofdlettergebruik, het late uur — is niet het bewijs van authenticiteit. Het is in deze werkomgeving een aangeleerde techniek. Het signaal waarop een abonnee vertrouwt om te bepalen of hij met een mens spreekt, is precies het signaal dat professioneel wordt nagebootst."),
  ("box", "Bewijsgrens",
   "Dat chat-vervanging bestaat en hoe zij georganiseerd is, staat vast: vier onafhankelijke redacties hebben het van binnenuit vastgelegd. Welk aandeel van alle gesprekken op alle platformen op deze manier verloopt, is niet vastgesteld en waarschijnlijk niet vast te stellen zonder medewerking van de platformen. Dit dossier doet daarover geen uitspraak."),
  ("h2", "Dezelfde techniek buiten het abonnementsmodel"),
  ("p", "De praktijk is niet tot één platform beperkt. NRC legde in juni 2025 een callcenter in Manila bloot waar medewerkers namens datingprofielen gesprekken voerden met Nederlandse gebruikers, ingericht rond een abonnementsmodel dat gebruikers naar eigen zeggen nauwelijks bewust afsloten. [BR-10] [BR-11] Dezelfde krant beschreef al in 2021 de zogeheten eWhoring-markt, waarin nepprofielen werden opgebouwd met van internet geplukte foto’s, voor 1,10 euro per profiel. [BR-12]"),
  ("p", "Wat die zaken verbindt, is niet de seksuele inhoud maar de architectuur: een geloofwaardig individu aan de voorkant, een arbeidsorganisatie aan de achterkant, en een betalingsstroom die gevoed wordt door de aanname van de gebruiker dat hij met dat individu spreekt."),
 ]},

{"num": "03", "part": "DEEL I — DE MARKT",
 "title": "Het bureau: contract, commissie en sleutelmacht",
 "deck": "Het beheerbureau is de minst zichtbare en meest bepalende partij in de keten. Wat het bureau precies mag, staat in contracten die geen van beide partijen publiceert — maar de werking ervan is inmiddels op drie manieren gedocumenteerd.",
 "blocks": [
  ("p", "In juni 2026 publiceerde de BBC het resultaat van maandenlang onderzoek naar de zogenoemde OFM-sector. De redactie sprak zestig Britse creators en werkte zich in in OFM Empire, een van de grootste besloten Telegram-groepen voor beheerders, met 24.000 leden. [BR-05] Dat is de eerste keer dat het interne verkeer van deze bedrijfstak op schaal is bekeken in plaats van via losse getuigenissen."),
  ("q", "We heard from 60 UK OnlyFans creators and embedded ourselves in one of the largest private Telegram groups for agents, called OFM Empire, which has 24,000 members.",
   "BBC News, 15 juni 2026 [BR-05]"),
  ("p", "Uit dat onderzoek komen drie vaststellingen die elkaar versterken: bureaus nemen doorgaans de helft van de inkomsten, zij oefenen operationele controle uit over het account, en er zijn bedreigingen vastgelegd tegen creators die eruit wilden. De BBC publiceerde daarvan een letterlijk bericht: ‘I will have you and your daughter wrote off.’ [BR-05] Dat is één bericht van één beheerder, en het bewijst niets over de sector als geheel. Het bewijst wel dat dreiging binnen deze relatievorm voorkomt en dat de creator die het ontvangt geen kant op kan zolang de tegenpartij het account beheert."),
  ("h2", "Waarom de sleutel belangrijker is dan het percentage"),
  ("p", "De commissie is het zichtbare deel van het contract; de toegang is het beslissende deel. Zodra een bureau over de inloggegevens, de gekoppelde betaalrekening, de identiteitsverificatie en de gespreksgeschiedenis beschikt, is de vraag of de creator mag vertrekken theoretisch geworden. Het Duitse onderzoek van SWR beschrijft een creator wier account door het bureau werd overgenomen: wachtwoord gewijzigd, alles gewist, het account aan iemand anders gegeven. [BR-14]"),
  ("q", "Passwort geändert, alles rausgelöscht und diesen Account dann jemand anderem gegeben.",
   "Creator ‘Laura’, in tagesschau / SWR VOLLBILD, 1 november 2022 [BR-14]"),
  ("p", "Balkan Insight documenteerde in november 2025 de financiële kant van dezelfde afhankelijkheid: een creator die bruto ongeveer 178.000 dollar opbracht en daarvan 10.000 dollar ontving. [BR-22] Daar is geen contractuele onduidelijkheid voor nodig; het volstaat dat de uitbetaling loopt via een rekening die de creator niet beheert."),
  ("table",
   [["ELEMENT", "WAT HET BUREAU DOORGAANS BEHEERT", "GEVOLG BIJ VERTREK"],
    ["Inloggegevens", "Wachtwoord, tweefactor, herstel-e-mail", "Geen toegang tot het eigen publiek"],
    ["Betaalstroom", "Gekoppelde rekening of tussenvennootschap", "Inkomsten blijven bij de tegenpartij"],
    ["Gespreksarchief", "CRM-database met abonneegegevens", "De relatie is niet overdraagbaar"],
    ["Beeldmateriaal", "Opgeslagen bibliotheek, soms met rechtenbeding", "Materiaal blijft exploiteerbaar"],
    ["Contract", "Looptijd, boetebeding, exclusiviteit", "Vertrek wordt financieel bestraft"]],
   [22, 48, 30]),
  ("h2", "Van dienstverlening naar zeggenschap"),
  ("p", "Juridisch presenteren deze bureaus zich als dienstverleners: marketing, planning, ondersteuning. Feitelijk beslissen zij in de gedocumenteerde gevallen over prijs, publicatieritme, gespreksinhoud en soms over wat er wordt gemaakt. De Guardian beschreef in juni 2026 hoe rond die bedrijfstak een tweede markt is ontstaan: cursussen die jongeren leren hoe ze zelf beheerder worden, verkocht in dezelfde stijl als andere online rijk-worden-programma’s. [BR-09] De sector reproduceert zichzelf via opleidingsproducten, niet via arbeidsmarktregulering."),
  ("p", "In België loopt inmiddels een strafzaak. Een vrouw verklaarde tegenover De Morgen dat zij onder druk pornografische video’s moest maken en dat haar beheerder dreigde haar familie in te lichten als zij weigerde. [BR-17] De Belgische sekswerker Mel Meliciousss formuleerde in dezelfde periode de verhouding die volgens haar zoek is geraakt: de manager hoort voor de maker te werken, niet andersom. [BR-18]"),
  ("q", "Bij gedwongen seksuele handelingen is sprake van prostitutie. Vrouwen op OnlyFans moeten beseffen dat zij niet voor zo’n manager werken. Die manager moet voor jou werken.",
   "Mel Meliciousss, in HLN, 16 juni 2026 [BR-18]"),
  ("box", "Bewijsgrens",
   "Dwang en bedreiging zijn in individuele, benoemde gevallen gedocumenteerd en in ten minste één geval strafrechtelijk voorgelegd. Dat rechtvaardigt geen uitspraak over alle bureaus. Wat wél voor de hele sector geldt, is structureel van aard: de contractvorm concentreert toegang, geld en archief bij één partij, waardoor misbruik goedkoop en vertrek duur wordt. Die structuur is toetsbaar zonder dat kwade trouw hoeft te worden aangetoond."),
 ]},

{"num": "04", "part": "DEEL II — DE MACHINERIE",
 "title": "Het gereedschap: wat de software zelf belooft",
 "deck": "Dit hoofdstuk citeert geen klokkenluiders maar verkoopteksten. De functionaliteit die critici de sector verwijten, staat woordelijk op de publieke productpagina’s van de leveranciers.",
 "blocks": [
  ("p", "De meest controleerbare bron over de werking van deze bedrijfstak is niet een lek maar een prijslijst. Drie leveranciers domineren het publieke aanbod van agency-software: Infloww, Supercreator en OnlyMonster. Hun marketing richt zich uitsluitend op bureaus en creators. De abonnee is in die teksten geen gesprekspartner maar een variabele."),
  ("h2", "Segmentatie op bestedingsvermogen"),
  ("p", "Infloww, dat stelt meer dan vijfduizend agentschappen te bedienen, beschrijft zijn functie ‘Smart lists’ als het groeperen van fans op basis van abonnementsduur en bestedingsvermogen, met het oog op gerichte retentie. Een tweede functie, ‘Priority mass messages’, plaatst een bericht in het voorrangstabblad van de ontvanger. De prijs is veertig dollar per maand per creatorprofiel. [BR-23]"),
  ("q", "Smart lists — Group fans based on subscription length and spending power for targeted retention.",
   "Infloww, publieke productpagina, geraadpleegd 19 september 2026 [BR-23]"),
  ("p", "Dat is een volwaardig CRM-vocabulaire, toegepast op gesprekken die aan de andere kant van het scherm als persoonlijk worden ervaren. ‘Retentie’ betekent hier: voorkomen dat iemand het abonnement opzegt. ‘Bestedingsvermogen’ betekent: hoeveel deze persoon vermoedelijk nog kan uitgeven."),
  ("h2", "Automatisering die zich als de creator presenteert"),
  ("p", "Supercreator adverteert met een AI-assistent die is getraind op naar eigen zeggen meer dan vijfhonderd miljoen gesprekken en verkopen, en met een AI-chatter die als volgt wordt beschreven: ‘Always on, always you… She chats with fans in your voice, sells your content automatically.’ [BR-24] De formulering laat aan duidelijkheid weinig te wensen over: het product is het overnemen van de stem."),
  ("q", "Always on, always you… She chats with fans in your voice, sells your content automatically.",
   "Supercreator, productpagina AI-chatter, geraadpleegd 19 september 2026 [BR-24]"),
  ("p", "Andere formuleringen van dezelfde leverancier: ‘Finds you hidden spenders’, ‘Bumps fans to spark engagement’, ‘Zero missed fans’, en op de agency-pagina de claim dat er gezamenlijk meer dan 180 miljoen dollar aan inkomsten is gegenereerd. De prijsstaffel schaalt mee met de omzet van de gebruiker: tot 1.000 dollar per maand, 1.000 tot 15.000, 15.000 tot 25.000, en daarboven. [BR-24] Ook dat is informatief: de leverancier deelt in de opbrengst en heeft dus hetzelfde belang als het bureau."),
  ("p", "OnlyMonster, dat 1.800 bedrijven in meer dan honderd landen claimt, biedt een functie die fans van nul tot vijf rangschikt naar bestedingspotentieel, waarschuwingen voor terugboekingsrisico, en een anti-detectiebrowser die elk account een eigen digitale vingerafdruk geeft. Diezelfde leverancier voegt expliciet toe dat de AI chatters ondersteunt in plaats van vervangt. [BR-25]"),
  ("table",
   [["FUNCTIE", "LETTERLIJKE AANDUIDING", "LEVERANCIER"],
    ["Segmentatie", "fans groeperen op abonnementsduur en bestedingsvermogen", "Infloww [BR-23]"],
    ["Voorranglevering", "bericht in het prioriteitstabblad van de ontvanger", "Infloww [BR-23]"],
    ["Spender-detectie", "“finds you hidden spenders”", "Supercreator [BR-24]"],
    ["Stemovername", "“chats with fans in your voice”", "Supercreator [BR-24]"],
    ["Scoring", "fans van 0 tot 5 op bestedingspotentieel", "OnlyMonster [BR-25]"],
    ["Detectieontwijking", "eigen digitale vingerafdruk per account", "OnlyMonster [BR-25]"]],
   [24, 52, 24]),
  ("h2", "De asymmetrie is contractueel, niet toevallig"),
  ("p", "De leveranciers doen niets illegaals door deze functies te verkopen. Segmentatie, massaberichten en geautomatiseerde antwoorden zijn in de reguliere e-commerce volstrekt gangbaar. Het verschil zit in de mededeling. Wie een nieuwsbrief van een webshop ontvangt, weet dat er een lijst bestaat. Wie een bericht ontvangt van iemand met wie hij meent een verhouding te hebben, weet dat niet — en de productpagina die het tegendeel documenteert is aan hem niet gericht."),
  ("q", "The software is openly advertised to management agencies but not disclosed to OnlyFans subscribers, who are left to assume they’re chatting in real time.",
   "Reuters, 30 juli 2024 [BR-02]"),
  ("box", "Bewijsgrens",
   "Wat op een productpagina staat, bewijst dat de functie wordt aangeboden — niet dat elk bureau haar gebruikt, en niet dat zij bij een bepaald account is ingezet. Dit dossier gebruikt deze bronnen daarom uitsluitend voor vaststellingen over het aanbod. Voor het gebruik ervan in concrete gesprekken steunt het op de journalistieke bronnen uit hoofdstuk 2."),
 ]},

{"num": "05", "part": "DEEL II — DE MACHINERIE",
 "title": "Het geheugen: intieme gegevens als bedrijfsmiddel",
 "deck": "Wat een abonnee vertelt over zijn scheiding, zijn overleden vader of zijn schulden, verdwijnt niet in de herinnering van een gesprekspartner. Het gaat naar een veld in een database die door meerdere mensen wordt gelezen.",
 "blocks": [
  ("p", "Om een gesprek over ploegendiensten heen te laten lopen, moet de kennis worden losgekoppeld van de persoon die haar opdeed. Dat gebeurt in notitievelden. De undercoververslagen van WIRED, SRF en GQ beschrijven alle drie dezelfde werkwijze: wat de abonnee prijsgeeft, wordt genoteerd zodat de volgende dienst erop kan voortbouwen. [BR-07] [BR-15] [BR-16] De CRM-leveranciers bieden precies daarvoor de velden, lijsten en scores aan. [BR-23] [BR-24] [BR-25]"),
  ("p", "Vanuit de abonnee gezien gebeurt er dan iets dat geen enkele interface hem meldt: een mededeling die hij deed in de veronderstelling van vertrouwelijkheid tussen twee personen, wordt een gedeeld bedrijfsmiddel met een bewaartermijn, een eigenaar en een commerciële functie."),
  ("h2", "Waarom dit juridisch zwaarder weegt dan gewone klantdata"),
  ("p", "Artikel 9, lid 1 van de Algemene verordening gegevensbescherming verbiedt in beginsel de verwerking van bijzondere categorieën persoonsgegevens, waaronder uitdrukkelijk gegevens over gezondheid en gegevens met betrekking tot iemands seksueel gedrag of seksuele gerichtheid. [BR-32] Een notitieveld waarin staat welke seksuele voorkeuren een abonnee heeft, of dat hij in behandeling is voor een depressie, valt naar de letter binnen die categorie."),
  ("q", "Verwerking van persoonsgegevens waaruit ras of etnische afkomst, politieke opvattingen, religieuze of levensbeschouwelijke overtuigingen […] blijken, en verwerking van gegevens over gezondheid of gegevens met betrekking tot iemands seksueel gedrag of seksuele gerichtheid is verboden.",
   "Artikel 9, lid 1 AVG [BR-32]"),
  ("p", "Daarbovenop komen de basisbeginselen van artikel 5: doelbinding, minimale gegevensverwerking, opslagbeperking en transparantie. [BR-32] Een abonnee heeft het recht te weten wie verwerkingsverantwoordelijke is, met welk doel zijn gegevens worden verwerkt, hoelang zij worden bewaard en aan wie zij worden doorgegeven. In de gedocumenteerde keten — platform, creator, bureau, softwareleverancier, chatter in een derde land — is geen van die vragen voor de abonnee beantwoordbaar."),
  ("ul", ["Wie is verwerkingsverantwoordelijke: het platform, de creator of het bureau? De gebruiksvoorwaarden wijzen naar de creator. [BR-06]",
          "Op welke grondslag worden bijzondere gegevens verwerkt? Toestemming voor artikel 9 moet uitdrukkelijk en geïnformeerd zijn; de abonnee weet niet dat er een dossier bestaat.",
          "Waar staan de gegevens? Chatters werken vanuit landen buiten de EER; een doorgiftegrondslag is nergens zichtbaar.",
          "Hoelang blijft het dossier bestaan? Bij overdracht van een account aan een ander bureau verhuist het gespreksarchief mee. [BR-14]"]),
  ("h2", "De grens die dit dossier niet overschrijdt"),
  ("p", "Het is verleidelijk om van ‘notities over kwetsbaarheden’ door te redeneren naar ‘een systeem dat psychische kwetsbaarheid classificeert om die te exploiteren’. Die stap is in dit dossier niet gezet, omdat het bewijs hem niet draagt. Wat vaststaat: er zijn notitievelden, er is segmentatie op bestedingsvermogen, en er zijn scorefuncties voor koopkracht. [BR-23] [BR-25] Wat niet vaststaat: dat er sectorbreed op psychische diagnose of mentale instabiliteit wordt gescoord. Die claim staat in het register als CL-14, met status onbevestigd."),
  ("box", "Wat dit zou bewijzen",
   "Om CL-14 van onbevestigd naar vastgesteld te brengen is nodig: een exportbestand of schermafdruk van een productieomgeving met velden of labels die op psychische toestand duiden, afkomstig van een identificeerbaar bureau, plus bevestiging door een tweede bron of een toezichthouder. Getuigenissen alleen volstaan hiervoor niet."),
  ("h2", "Profilering en het recht om er niet aan onderworpen te zijn"),
  ("p", "Artikel 22 AVG beperkt besluitvorming die uitsluitend op geautomatiseerde verwerking berust en die de betrokkene in aanmerkelijke mate treft. [BR-32] Of het automatisch selecteren van een abonnee voor een verkoopcampagne op grond van zijn bestedingsscore daaronder valt, is een open juridische vraag; de economische gevolgen kunnen aanzienlijk zijn, maar de drempel van ‘rechtsgevolg of vergelijkbare aanmerkelijke treffing’ is niet vanzelfsprekend gehaald. Dit dossier stelt de vraag; het beantwoordt haar niet."),
  ("p", "Wel eenduidig is artikel 26, lid 3 van de digitaledienstenverordening: aanbieders van onlineplatformen mogen geen reclame tonen op basis van profilering met bijzondere categorieën persoonsgegevens in de zin van artikel 9 AVG. [BR-33] Zodra de gerichte verkoopberichten binnen een platform als reclame kwalificeren en de segmentatie op seksuele voorkeur berust, raakt die bepaling rechtstreeks aan de beschreven praktijk."),
 ]},

{"num": "06", "part": "DEEL II — DE MACHINERIE",
 "title": "Het script: anatomie van een geoefend gesprek",
 "deck": "Dit hoofdstuk reconstrueert de gesprekstechniek uit gepubliceerd trainingsmateriaal. Het is een reconstructie, geen uitgelekt handboek — en het is als zodanig gemarkeerd.",
 "blocks": [
  ("p", "Drie journalisten hebben de opleiding doorlopen en hun instructies gepubliceerd. [BR-07] [BR-15] [BR-16] Daaruit valt de techniek te reconstrueren. Wat volgt is dus een geordende samenvatting van gepubliceerde instructies, geen origineel intern document. Waar een fase op letterlijk gepubliceerd materiaal berust, staat de bron erbij; waar zij op patroonherkenning berust, staat dat er ook."),
  ("h3", "STATUS VAN DIT HOOFDSTUK: RECONSTRUCTIE"),
  ("p", "De reconstructie beschrijft vier fasen. Zij komen niet in elk gesprek voor en niet in deze volgorde. Zij beschrijven wat het trainingsmateriaal als doel stelt, niet wat elke chatter doet."),
  ("h2", "Fase 1 — Onderscheiding"),
  ("p", "De abonnee wordt van andere abonnees onderscheiden: hij is anders, attenter, beschaafder dan de rest. De functie is dubbel. Zij verlaagt de kritische houding en zij verschuift de verhouding van transactie naar uitzondering. Het bijbehorende instructiedoel uit het SRF-materiaal is expliciet gericht op het warm houden van de fan met het oog op aankoop. [BR-16]"),
  ("h2", "Fase 2 — Wederkerige onthulling"),
  ("p", "De chatter deelt iets persoonlijks, waarna de abonnee dat beantwoordt. Wat hij deelt gaat het notitieveld in (hoofdstuk 5). De wederkerigheid is eenzijdig: de ene onthulling is een gespreksinstrument, de andere is een feit over een bestaand leven. Schuchmann beschrijft deze aangeleerde omgang met authenticiteit als emotionele arbeid: het vertellen van het verhaal dat de ander die dag wil horen. [BR-27]"),
  ("q", "I tell them the story that they want to hear that day.",
   "Creator, geciteerd in Swana Schuchmann, Porn Studies, 9 juni 2025 [BR-27]"),
  ("h2", "Fase 3 — Aanleiding tot betaling"),
  ("p", "Er ontstaat een reden om nu te betalen: een aanbod dat aflopt, een situatie die zich voordoet, een exclusief bericht. In het door SRF gepubliceerde materiaal is het doel van de fase omzetverhoging; de concrete aanleiding varieert per bureau. Verhalen over gefabriceerde noodsituaties komen in getuigenissen voor, maar zijn in dit dossier niet met primair materiaal onderbouwd en worden daarom als onbevestigd gemarkeerd."),
  ("h2", "Fase 4 — Uitstel als bindmiddel"),
  ("p", "De ontmoeting, het telefoongesprek of de bevestiging wordt in het vooruitzicht gesteld en verschoven. Uitstel houdt het gesprek open. Dit patroon is herkenbaar uit het door NRC beschreven callcenter in Manila, waar het gesprek zelf het product was en de ontmoeting het permanente vooruitzicht. [BR-10]"),
  ("q", "Sariah: Denk je dat het lang zal duren tussen ons, lieverd? — Nathan: Ik hou zoveel van je dat ik de rest van mijn leven met je wil doorbrengen.",
   "Chatverkeer uit een callcenter in Manila, vastgelegd door NRC, 30 juni 2025 [BR-10]"),
  ("h2", "De vraag die het gesprek niet kan beantwoorden"),
  ("p", "In het Reuters-onderzoek stelt een abonnee de enige vraag die ertoe doet — spreek ik met jou? — en krijgt hij een antwoord dat de vraag wegneemt zonder haar te beantwoorden. [BR-01] Dat is structureel: binnen het gesprek bestaat geen mechanisme waarmee de vraag betrouwbaar kan worden beantwoord. Elk antwoord is tekst, en tekst is precies wat het bureau levert. Daarom kan dit probleem niet door oplettendheid van de abonnee worden opgelost, en daarom is het een informatieprobleem en geen karakterkwestie."),
  ("box", "Bewijsgrens",
   "Vastgesteld is dat er trainingsmateriaal bestaat dat gespreksvoering op verkoop richt, en dat drie journalisten dat materiaal hebben ontvangen en gepubliceerd. Niet vastgesteld is dat er één sectorbreed script bestaat, of dat gefabriceerde noodsituaties standaardpraktijk zijn. De vierfasenstructuur in dit hoofdstuk is een analytisch model van de auteur."),
 ]},

{"num": "07", "part": "DEEL III — HET RECHT",
 "title": "Consumentenrecht: misleiding zonder leugen",
 "deck": "De kernvraag is niet of iemand liegt, maar of essentiële informatie wordt weggelaten die het aankoopbesluit bepaalt. Daarvoor bestaat een Europese norm — en er is inmiddels rechtspraak.",
 "blocks": [
  ("p", "Richtlijn 2005/29/EG over oneerlijke handelspraktijken kent twee relevante figuren. Artikel 6 verbiedt de misleidende handeling: informatie die feitelijk onjuist is of de gemiddelde consument bedriegt of kan bedriegen ten aanzien van onder meer de voornaamste kenmerken van het product, en die hem tot een besluit brengt dat hij anders niet had genomen. Artikel 7 verbiedt de misleidende omissie: het weglaten of verhullen van essentiële informatie die de consument nodig heeft om een geïnformeerd besluit te nemen. [BR-31]"),
  ("p", "Artikel 7 is hier het scherpst. Bij betaalde één-op-één-communicatie is de identiteit van de gesprekspartner geen bijkomstigheid maar het voornaamste kenmerk van wat wordt gekocht. Wie een bericht koopt van een specifiek persoon, koopt dat persoon. Wordt niet meegedeeld dat een derde schrijft, dan ontbreekt precies de informatie die het besluit bepaalt."),
  ("h2", "Een rechter die dat zo uitsprak"),
  ("p", "In december 2025 verbood het Landgericht Hamburg het platform Fanblast om betaalde WhatsApp-gesprekken met vermeende influencers aan te bieden. De rechter kwalificeerde de praktijk als misleiding, omdat de gesprekken in werkelijkheid werden gevoerd door bureaus die de schrijfstijl van bekende personen imiteerden. [BR-38] Dat is, voor zover in dit dossier vastgesteld, de eerste Europese uitspraak waarin niet-gemelde chat-vervanging expliciet als misleidend is aangemerkt."),
  ("p", "In de Verenigde Staten loopt dezelfde vraag via twee collectieve procedures. In McFadden en DeFranza tegen Fenix Internet (N.D. Ill., 2023) draait het om de marketingbelofte van authentieke relaties. [BR-04] In N.Z. e.a. tegen Fenix International c.s. (C.D. Cal., zaaknummer 8:24-cv-01655) zijn naast het platform acht beheerbureaus gedagvaard, waaronder Boss Baddies, Moxy Management, Unruly Agency, Behave Agency, A.S.H. Agency, Content X, Verge Agency en Elite Creators. De klacht stelt dat het platform fans authentieke en directe verbindingen met creators belooft en de chat-praktijk toelaat omdat zij er financieel bij vaart. [BR-03]"),
  ("q", "OnlyFans allows the ‘Chatter Scams’ because it financially benefits OnlyFans.",
   "Klacht in N.Z. e.a. v. Fenix International Ltd. e.a., zaaknr. 8:24-cv-01655 (C.D. Cal.) [BR-03]"),
  ("box", "Status",
   "Een dagvaarding is een standpunt van een eisende partij, geen vaststelling. Dit dossier gebruikt de procedures als bewijs dat de vraag rechterlijk voorligt en welke feiten daarin worden gesteld — niet als bewijs dat die feiten juist zijn. De Hamburgse uitspraak is wel een beslissing, maar met beperkte reikwijdte: één platform, één land, één feitencomplex."),
  ("h2", "Wie is de handelaar?"),
  ("p", "Het platform wijst naar zijn voorwaarden: de zakelijke relatie bestaat uitsluitend met de creator. [BR-06] De creator wijst in de gedocumenteerde gevallen naar het bureau, dat het gesprek voert en de opbrengst int. Het bureau heeft geen contractuele relatie met de abonnee en is voor hem onzichtbaar. Het resultaat is een keten waarin iedereen dienstverlener van een ander is en niemand jegens de betalende partij verantwoordelijk lijkt."),
  ("p", "Consumentenrechtelijk is dat minder solide dan het klinkt. De richtlijn knoopt aan bij de handelspraktijk en bij wie haar verricht of laat verrichten, niet bij de vraag wie op papier contractspartij is. [BR-31] Een bureau dat beroepsmatig namens een creator met consumenten communiceert met het oog op verkoop, verricht een handelspraktijk. Dat die communicatie onder andermans naam plaatsvindt, maakt haar niet minder een handelspraktijk — het is juist het kenmerk dat haar mogelijk misleidend maakt."),
  ("h2", "Wat een toezichthouder morgen zou kunnen doen"),
  ("ul", ["Een informatieverzoek aan platformen over het aandeel accounts dat via derden wordt beheerd en of dat wordt geregistreerd.",
          "Een mystery-shoponderzoek naar de vraag of de identiteitsvraag in betaalde chats naar waarheid wordt beantwoord.",
          "Handhaving op artikel 7 UCPD bij bureaus die in de EU gevestigd zijn en aantoonbaar namens creators schrijven.",
          "Toetsing van de keten aan artikel 26, lid 3 DSA waar segmentatie op seksuele voorkeur berust. [BR-33]"]),
 ]},

{"num": "08", "part": "DEEL III — HET RECHT",
 "title": "De lacune: AI moet zich melden, de mens niet",
 "deck": "Sinds 2 augustus 2026 moet een systeem melden dat het geen mens is. Voor een mens die zich als iemand anders voordoet, bestaat geen vergelijkbare meldplicht. Dat is het scherpste juridische gat in dit dossier.",
 "blocks": [
  ("p", "Artikel 50, lid 1 van de AI-verordening verplicht aanbieders ervoor te zorgen dat AI-systemen die rechtstreeks met natuurlijke personen interageren zo worden ontworpen dat die personen weten dat zij met een AI-systeem te maken hebben, tenzij dat gelet op de omstandigheden evident is. De bepaling is van toepassing vanaf 2 augustus 2026. [BR-34]"),
  ("q", "Providers shall ensure that AI systems intended to interact directly with natural persons are designed and developed in such a way that the natural persons concerned are informed that they are interacting with an AI system, unless this is obvious…",
   "Artikel 50, lid 1, Verordening (EU) 2024/1689 [BR-34]"),
  ("p", "Toegepast op deze markt is dat een aanzienlijke verandering. Een product dat wordt verkocht met de belofte dat het in de stem van de creator met fans chat en automatisch verkoopt [BR-24], is een AI-systeem dat rechtstreeks met natuurlijke personen interageert. Is het antwoord geheel of in doorslaggevende mate door dat systeem opgesteld, dan ligt er vanaf augustus 2026 een informatieplicht."),
  ("h2", "En daar houdt het op"),
  ("p", "De verordening regelt de verhouding mens–machine. Zij regelt niet de verhouding mens–mens-onder-andermans-naam. Een chatter in Manilla die namens een creator in Amsterdam schrijft, valt buiten artikel 50: er is geen AI-systeem, er is een arbeidsorganisatie. Voor dat geval bestaat geen expliciete Europese meldplicht. Wat rest is de open norm van artikel 7 UCPD, die per geval moet worden getoetst door een rechter of toezichthouder, met alle bewijslast die daarbij hoort. [BR-31]"),
  ("table",
   [["SITUATIE", "GELDENDE NORM", "MELDPLICHT"],
    ["Antwoord gegenereerd door AI", "Art. 50 AI-verordening [BR-34]", "Ja, vanaf 2 aug. 2026"],
    ["Antwoord door AI voorgesteld, door mens verzonden", "Onduidelijk; afhankelijk van mate van sturing", "Ongeregeld"],
    ["Antwoord door betaalde chatter namens creator", "Art. 6–7 UCPD, per geval [BR-31]", "Geen expliciete plicht"],
    ["Advertentie op basis van bijzondere gegevens", "Art. 26 lid 3 DSA [BR-33]", "Verbod op die profilering"],
    ["Manipulatief interfaceontwerp", "Art. 25 DSA [BR-33]", "Verbod"]],
   [34, 40, 26]),
  ("p", "De middelste rij is de meest waarschijnlijke praktijk en tegelijk de minst geregelde. De leveranciers zelf benadrukken dat hun AI de chatter ondersteunt in plaats van vervangt. [BR-25] Precies die formulering plaatst het product in de ongeregelde tussenruimte: te menselijk voor artikel 50, te geautomatiseerd voor de aanname van een persoonlijk gesprek."),
  ("h2", "Artikel 25 DSA: het ontwerp zelf"),
  ("q", "Aanbieders van onlineplatformen mogen hun online-interfaces niet zodanig ontwerpen, organiseren of exploiteren dat gebruikers worden misleid of gemanipuleerd of dat hun vermogen om vrije en geïnformeerde beslissingen te nemen anderszins wezenlijk wordt verstoord of belemmerd.",
   "Artikel 25, lid 1, Verordening (EU) 2022/2065 (DSA) [BR-33]"),
  ("p", "Deze bepaling richt zich op het platform, niet op het bureau. Zij is relevant zodra een interface de indruk van directe persoonlijke communicatie wekt en tegelijk geen enkele mogelijkheid biedt om te achterhalen wie schrijft. Of dat ‘wezenlijk verstoren’ oplevert, is niet uitgemaakt. Het is wel een vraag die een toezichthouder kan stellen zonder eerst één specifiek bureau te hoeven bewijzen."),
  ("box", "De kern van de lacune in één zin",
   "Vanaf augustus 2026 heeft de Europese consument recht op de mededeling dat hij met een machine praat, maar niet op de mededeling dat hij met een andere mens praat dan degene wiens naam, gezicht en stem hij betaalt."),
 ]},

{"num": "09", "part": "DEEL III — HET RECHT",
 "title": "Lex Humanitas Digitalis — een modelvoorstel",
 "deck": "Geen geldend recht en geen juridisch advies: een concreet geformuleerd voorstel dat de lacune uit het vorige hoofdstuk dicht, opgeschreven zodat er inhoudelijk tegen te argumenteren valt.",
 "blocks": [
  ("p", "Kritiek zonder voorstel blijft houding. Wat volgt is een modeltekst in vijf artikelen, geschreven op het niveau waarop een Europese informatieplicht zou moeten werken: specifiek genoeg om te handhaven, beperkt genoeg om geen legitieme dienstverlening te verbieden. De tekst is een voorstel van de auteur en heeft geen enkele juridische status."),
  ("h3", "ARTIKEL 1 — IDENTITEITSMEDEDELING"),
  ("p", "Wie beroepsmatig tegen betaling één-op-één-communicatie aanbiedt onder de naam of beeltenis van een natuurlijke persoon, deelt vóór de eerste betaalde uitwisseling mee of berichten worden opgesteld door die persoon, door een gemachtigde derde, of geheel of gedeeltelijk door een geautomatiseerd systeem. De mededeling is permanent zichtbaar in de gespreksomgeving en niet weg te klikken."),
  ("h3", "ARTIKEL 2 — HET RECHT OP EEN WAARHEIDSGETROUW ANTWOORD"),
  ("p", "Op de rechtstreekse vraag van een consument wie het bericht heeft opgesteld, wordt naar waarheid geantwoord. Een onjuist antwoord op die vraag geldt als misleidende handeling in de zin van artikel 6 van richtlijn 2005/29/EG. Deze bepaling is de kern: zij verplaatst het gat van de open norm naar een concreet, bewijsbaar feit."),
  ("h3", "ARTIKEL 3 — GEGEVENSBEPERKING IN INTIEME CONTEXT"),
  ("p", "Gegevens over gezondheid, seksueel gedrag, rouw, verslaving of financiële nood die in betaalde persoonlijke communicatie worden prijsgegeven, mogen niet worden gebruikt voor segmentatie, doelgroepbepaling of geautomatiseerde verkoopsturing. Bewaartermijn en ontvangers worden op verzoek onverwijld meegedeeld. Deze bepaling verscherpt en concretiseert wat artikel 9 AVG al verbiedt. [BR-32]"),
  ("h3", "ARTIKEL 4 — CONTRACTUELE UITGANG VOOR DE MAKER"),
  ("p", "Een overeenkomst tussen maker en beheerder is nietig voor zover zij de maker permanente toegang tot het eigen account, tot de eigen inkomstenstroom en tot een export van haar publiek en beeldmateriaal ontzegt. Opzegtermijnen van meer dan drie maanden en boetebedingen boven de werkelijk geleden schade zijn niet afdwingbaar. Dit artikel beantwoordt rechtstreeks aan de in hoofdstuk 3 gedocumenteerde sleutelmacht. [BR-05] [BR-14] [BR-22]"),
  ("h3", "ARTIKEL 5 — CONTROLEERBAARHEID"),
  ("p", "Platformen houden bij welke accounts door derden worden beheerd en maken dat aantal jaarlijks geaggregeerd openbaar. Toezichthouders kunnen steekproefsgewijs verifiëren of de mededeling uit artikel 1 correct is. Zonder deze bepaling blijven de voorgaande vier onbewijsbaar."),
  ("h2", "Voorzienbare tegenwerpingen"),
  ("ul", ["‘Dit vernietigt de illusie waarvoor mensen betalen.’ — De mededeling betreft wie schrijft, niet wat wordt geschreven. Fictie blijft toegestaan; het auteurschap wordt vermeld, zoals bij elk ander cultureel product.",
          "‘Creators hebben ondersteuning nodig.’ — Artikel 1 verbiedt ondersteuning niet. Het verbiedt het verzwijgen ervan tegenover de betalende partij.",
          "‘Dit is niet handhaafbaar over de grens.’ — Dat geldt voor het volledige consumentenacquis en is nooit een argument geweest om de norm dan maar niet te stellen. Artikel 5 maakt de norm meetbaar bij de partij die wél binnen bereik is: het platform.",
          "‘De abonnee weet het eigenlijk wel.’ — De gedocumenteerde reacties van abonnees weerspreken dat, en het is bovendien geen juridisch criterium: de maatstaf is de gemiddelde consument, niet de best geïnformeerde. [BR-01] [BR-31]"]),
 ]},

{"num": "10", "part": "DEEL IV — DE GRENZEN",
 "title": "Wat dit dossier niet bewijst",
 "deck": "Het zwakste deel van een onderzoek is de plaats waar een auteur doorredeneert voorbij zijn materiaal. Dit hoofdstuk benoemt die plaatsen expliciet en degradeert vier beweringen die elders in dit project eerder te stellig zijn gebracht.",
 "blocks": [
  ("p", "Een dossier dat alleen bevestigt wat de auteur al vond, is een pamflet. Wat volgt zijn de beweringen die dit onderzoek niet kan dragen, met de reden waarom niet en met de aanduiding van het bewijs dat ze alsnog zou kunnen dragen."),
  ("h2", "1. Micro-transacties als witwas- en cardingkanaal"),
  ("p", "De stelling dat virale verkoophypes op sociale platformen op grote schaal dienen als dekmantel voor het testen van gestolen kaartgegevens, is in dit onderzoek niet onderbouwd. Er is geen opsporingsbron, geen toezichtsrapport en geen rechtbankdossier gevonden dat dit staaft voor deze specifieke markt. Fraude met terugboekingen bestaat aantoonbaar — de CRM-leveranciers verkopen er waarschuwingsfuncties voor [BR-25] — maar dat is iets anders dan een georganiseerde witwasstraat. Status: onbevestigd (CL-15). Vereist bewijs: een strafdossier, een rapport van een financiële toezichthouder of een gedocumenteerd patroon van een betaaldienstverlener."),
  ("h2", "2. Demografische effecten"),
  ("p", "De gedachte dat deze bedrijfstak meetbaar bijdraagt aan dalende geboortecijfers of aan het uitblijven van relatievorming, is niet getoetst en waarschijnlijk niet toetsbaar met de beschikbare gegevens. Geboortecijfers dalen in vrijwel alle hoge-inkomenslanden om redenen die uitvoerig bestudeerd zijn — woonkosten, arbeidsparticipatie, uitgestelde gezinsvorming. Eén bedrijfstak daaruit isoleren als oorzaak is methodologisch onhoudbaar. Status: onbevestigd (CL-16)."),
  ("h2", "3. Het ‘90 procent’-getal"),
  ("p", "In eerdere versies van dit manuscript stond dat het beeld van de zelfstandige maker bij minstens negentig procent van de topprofielen een constructie is. Dat getal heeft geen bron. Het wordt hierbij ingetrokken. Wat wél gesteld kan worden: bij accounts met grote volumes is individuele beantwoording fysiek onmogelijk, en uitbesteding is bij toppagina’s gedocumenteerd. [BR-01] Een percentage hoort daar niet bij zolang niemand telt."),
  ("h2", "4. Het maatschappelijke complot"),
  ("p", "De stelling dat deze bedrijfstak bewust wantrouwen tussen mannen en vrouwen aanjaagt om vervolgens de oplossing te verkopen, is in dit dossier een hypothese en geen vaststelling (CL-17). Er is geen bron die een intentie aantoont. Wat wel verdedigbaar is, is een economische observatie zonder intentie: een markt die vraag ondervindt uit eenzaamheid heeft geen belang bij afnemende eenzaamheid. Dat is een belangenanalyse, geen samenzwering, en het onderscheid is niet cosmetisch — het is het verschil tussen een argument dat standhoudt en een dat zichzelf diskwalificeert."),
  ("box", "Waarom deze afbakening het dossier sterker maakt",
   "Iedere weerlegde claim in een dossier besmet de claims die wél kloppen. Door CL-15 tot en met CL-17 expliciet buiten het feitelijke deel te houden, blijft wat overblijft — chat-vervanging, commissiestructuren, sleutelmacht, segmentatiesoftware, de juridische lacune — onaantastbaar met bronnen die iedereen kan natrekken."),
  ("h2", "Wat wél vaststaat, in één alinea"),
  ("p", "Betaalde chatters schrijven namens creators zonder dat abonnees dat weten; dat is door vier redacties van binnenuit vastgelegd. Software voor die praktijk wordt openlijk verkocht met segmentatie op bestedingsvermogen en met AI die in de stem van de creator schrijft. Bureaus nemen de helft tot twee derde van de inkomsten en beheren in gedocumenteerde gevallen de toegang tot account, geld en archief. Er zijn bedreigingen vastgelegd en er loopt een strafzaak. Twee Amerikaanse collectieve procedures en één Duitse uitspraak behandelen de praktijk als mogelijke of vastgestelde misleiding. Vanaf augustus 2026 moet AI zich melden; de menselijke plaatsvervanger niet. Dat is het dossier. Het is genoeg."),
 ]},

{"num": "11", "part": "DEEL IV — DE GRENZEN",
 "title": "Methodologie, wederhoor en correctiebeleid",
 "deck": "Hoe dit dossier is samengesteld, welke bronsoorten welk gewicht krijgen, wat er niet is gedaan en hoe fouten worden hersteld.",
 "blocks": [
  ("h2", "Bewijsladder"),
  ("p", "Bronnen zijn niet gelijkwaardig. Dit dossier hanteert vier niveaus. Ten eerste primaire documenten: jaarrekeningen, wetteksten, processtukken en publieke productpagina’s van leveranciers. Deze wegen het zwaarst omdat iedere lezer ze kan openen. Ten tweede onderzoeksjournalistiek van redacties met een gepubliceerde werkwijze en rechtzettingsbeleid, in het bijzonder waar de journalist zelf binnen de praktijk heeft gewerkt. Ten derde wetenschappelijk werk met beschreven methode en steekproef. Ten vierde losse getuigenissen, die in dit dossier nooit alleen een vaststelling dragen."),
  ("h2", "Wat niet is gedaan"),
  ("ul", ["Er is geen wederhoor gevraagd aan de genoemde platformen, bureaus en softwareleveranciers. Dit is een documentanalyse op basis van openbaar materiaal; dat is een beperking en wordt hier als zodanig benoemd.",
          "Er is geen eigen undercoveronderzoek verricht. Alle beschrijvingen van de werkvloer zijn ontleend aan journalisten die dat wel deden.",
          "Er zijn geen individuele accounts, creators of abonnees geïdentificeerd. Namen komen uitsluitend voor waar zij al gepubliceerd zijn in de bronnen.",
          "Er is geen kwantitatieve schatting gemaakt van de omvang van chat-vervanging. Alle circulerende percentages missen een controleerbare basis."]),
  ("h2", "Omgang met het manuscriptmateriaal"),
  ("p", "Dit project begon als een verzameling essays en aantekeningen met een aanzienlijk speculatief deel. Bij de samenstelling van deze editie is dat materiaal getoetst aan de bronnen. Wat standhield, staat in de delen I tot en met III. Wat niet standhield, staat in hoofdstuk 10 en in het claimregister met de status onbevestigd of hypothese. Niets uit het oorspronkelijke materiaal is stilzwijgend blijven staan; de literaire bewerking ervan leeft voort in de leeseditie, waar zij als interpretatie herkenbaar is."),
  ("h2", "Correctiebeleid"),
  ("p", "Een feitelijke onjuistheid wordt gecorrigeerd zodra zij met bron wordt gemeld, en de correctie wordt vermeld in de versiegeschiedenis van de online-editie. Claims kunnen van status veranderen in beide richtingen. Een claim die naar beneden wordt bijgesteld, blijft zichtbaar in het register met vermelding van de reden; hij wordt niet verwijderd. De online-editie is leidend; de vaste uitgave draagt een versiedatum."),
  ("h2", "Belangenverklaring"),
  ("p", "De auteur ontvangt geen vergoeding van enige partij in de beschreven markt, van geen platform, geen bureau, geen leverancier en geen belangenorganisatie. Er is geen betaalde toegang tot dit dossier. De publicaties zijn vrij te verspreiden voor onderwijs- en onderzoeksdoeleinden."),
 ]},
]
