# -*- coding: utf-8 -*-
"""Bronnen-, claim- en chronologieregister.

Elke bewering in de publicaties verwijst naar een code uit SOURCES.
Status in CLAIMS is bewust strikt:
  VASTGESTELD  – meervoudig gedocumenteerd in primaire of onafhankelijke bronnen
  GEDOCUMENTEERD – één degelijke bron, nog niet onafhankelijk bevestigd
  BETWIST      – bron en wederpartij spreken elkaar tegen
  ONBEVESTIGD  – plausibel, maar zonder controleerbaar bewijs in dit dossier
  HYPOTHESE    – interpretatiekader van de auteur, geen feitelijke vaststelling
"""

SOURCES = [
    ("BR-01", "Onderzoeksjournalistiek", "Reuters — “OnlyFans’ porn juggernaut fueled by a deception”",
     "Andrew R.C. Marshall, Jason Szep, Linda So · 30 juli 2024",
     "reuters.com/investigates/special-report/onlyfans-sex-chatters/"),
    ("BR-02", "Onderzoeksjournalistiek", "Reuters — “AI bots talk dirty so OnlyFans stars don’t have to”",
     "30 juli 2024",
     "reuters.com/technology/artificial-intelligence/ai-bots-talk-dirty-so-onlyfans-stars-dont-have-2024-07-30/"),
    ("BR-03", "Procesdossier", "N.Z. e.a. v. Fenix International Ltd. e.a., zaaknr. 8:24-cv-01655-FWS-SSC",
     "U.S. District Court, Central District of California · dagvaarding 2024, gewijzigde klacht 23 april 2025",
     "storage.courtlistener.com/recap/gov.uscourts.cacd.935040/"),
    ("BR-04", "Procesdossier", "McFadden & DeFranza v. Fenix Internet LLC, zaaknr. 1:23-cv-06151",
     "U.S. District Court, Northern District of Illinois · 2023",
     "storage.courtlistener.com/recap/gov.uscourts.ilnd.437583/"),
    ("BR-05", "Onderzoeksjournalistiek", "BBC News — “OnlyFans ‘agents’ control and threaten creators while taking half their earnings”",
     "Natasha Cox, Amelia Ellis, Kirstie Brewer, Mike Radford · 15 juni 2026",
     "bbc.com/news/articles/c932gpk2l1do"),
    ("BR-06", "Onderzoeksjournalistiek", "BBC News — “‘Icky and heartbreaking’: Life as an OnlyFans ‘chatter’”",
     "Chris Vallance · 11 maart 2026", "bbc.com/news/articles/cq571g9gd4lo"),
    ("BR-07", "Reportage", "WIRED — “I Went Undercover as a Secret OnlyFans Chatter”",
     "Brendan I. Koerner · 15 mei 2024",
     "wired.com/story/i-went-undercover-secret-onlyfans-chatter-wasnt-pretty/"),
    ("BR-08", "Reportage", "VICE — “Think You’re Messaging an OnlyFans Star? You’re Talking to These Guys”",
     "oktober 2023", "vice.com/en/article/onlyfans-management-agency-chatters/"),
    ("BR-09", "Onderzoeksjournalistiek", "The Guardian — “The malignant rise of OnlyFans managers”",
     "Amelia Gentleman · 18 juni 2026",
     "theguardian.com/society/2026/jun/18/malignant-rise-onlyfans-managers-exploiting-grooming-predatory"),
    ("BR-10", "Onderzoeksjournalistiek", "NRC — “Seks-chatten met het callcenter in Manila”",
     "Rik Wassens & Tom Kreling · 30 juni 2025", "nrc.nl/nieuws/2025/06/30/a4898808"),
    ("BR-11", "Onderzoeksjournalistiek", "NRC — “Klik, klik, en ineens heb je een abonnement zonder dat je het weet”",
     "Rik Wassens & Tom Kreling · 27 juni 2025", "nrc.nl/nieuws/2025/06/27/a4898085"),
    ("BR-12", "Reportage", "NRC — “De vrouw die jou haar naaktfoto’s wil verkopen, die is nep” (eWhoring)",
     "Juliët Boogaard · 14 juni 2021", "nrc.nl/nieuws/2021/06/14/a4047252"),
    ("BR-13", "Onderzoeksjournalistiek", "Der Spiegel — “Das fragwürdige Geschäft mit Erotik und Pseudo-Intimität”",
     "Böhm, Knigge & Neumann · 21 april 2025", "spiegel.de/netzwelt/web/onlyfans-a-90bce533"),
    ("BR-14", "Onderzoeksjournalistiek", "tagesschau / SWR «VOLLBILD» — OnlyFans en externe agentschappen",
     "1 november 2022", "tagesschau.de/investigativ/onlyfans-externe-agenturen-101.html"),
    ("BR-15", "Reportage", "GQ Duitsland — undercover als chatter (Ella Fleck)",
     "20 augustus 2026", "gq-magazin.de/artikel/undercover-bei-onlyfans-ella-fleck-chat-agenturen-maenner"),
    ("BR-16", "Reportage", "SRF «DOK» — “Betrug mit Sexting: Ghostwriter zocken auf OnlyFans Männer ab”",
     "Ilona Stämpfli · 16 januari 2024", "srf.ch/sendungen/dok/betrug-mit-sexting"),
    ("BR-17", "Rechtbankverslag", "De Morgen — “In de klauwen van de e-pooier” (strafzaak G.W., zitting september 2026)",
     "Eline Bergmans · 27 juli 2026", "demorgen.be/nieuws/~b6f337a0/"),
    ("BR-18", "Interview", "HLN — sekswerker Mel Meliciousss over ‘nieuwe pooiers’",
     "Luc Beernaert · 16 juni 2026", "hln.be/nieuws/~a321601b/"),
    ("BR-19", "Onderzoeksjournalistiek", "Rappler — tweeluik over Filipijnse editors en chatters",
     "Shay Du · 4–5 februari 2026", "rappler.com/newsbreak/in-depth/behind-onlyfans-filipino-workers/"),
    ("BR-20", "Journalistiek", "Nikkei Asia — “Filipino OnlyFans ‘chatters’ struggle with mental health, job security”",
     "Michael Beltran · 21 oktober 2025", "asia.nikkei.com/spotlight/society/"),
    ("BR-21", "Journalistiek", "Rest of World — “AI threatens jobs of Filipinos running DMs”",
     "Michael Beltran · 20 augustus 2025", "restofworld.org/2025/onlyfans-ai-dm-bots/"),
    ("BR-22", "Onderzoeksjournalistiek", "Balkan Insight — “From OnlyFans to OnlyScams”",
     "Bohmer, Maia & Rychlikova · 13 november 2025",
     "balkaninsight.com/2025/11/13/from-onlyfans-to-onlyscams/"),
    ("BR-23", "Productdocumentatie", "Infloww — publieke product- en prijspagina’s (agency-CRM)",
     "geraadpleegd 19 september 2026", "infloww.com"),
    ("BR-24", "Productdocumentatie", "Supercreator — publieke product-, agency- en prijspagina’s",
     "geraadpleegd 19 september 2026", "supercreator.app"),
    ("BR-25", "Productdocumentatie", "OnlyMonster — publieke agency- en prijspagina’s",
     "geraadpleegd 19 september 2026", "onlymonster.ai/agency"),
    ("BR-26", "Wetenschappelijk", "Pierre Brasseur, “Beyond the Gig: Selling Intimacy as Labour on OnlyFans”, British Journal of Sociology",
     "2026 · 45 diepte-interviews (FR/BE/CH), analyse van 14 versies van de gebruiksvoorwaarden 2019–2025",
     "dipot.ulb.ac.be/dspace/bitstream/2013/412310/3/BJS2026.pdf"),
    ("BR-27", "Wetenschappelijk", "Swana Schuchmann, “I tell them the story that they want to hear that day”, Porn Studies",
     "9 juni 2025 · emotionele arbeid en authenticiteit bij vijf Duitse creators",
     "doi.org/10.1080/23268743.2025.2501322"),
    ("BR-28", "Wetenschappelijk", "Sexuality & Culture — grens-, blootstellings- en impressiemanagement bij Ierse modellen",
     "29 april 2024", "doi.org/10.1007/s12119-024-10230-2"),
    ("BR-29", "Wetenschappelijk", "Sebastiaan Gorissen, “Countering digital labor platforms’ algorithmic management”, Convergence",
     "24 september 2025", "doi.org/10.1177/13548565251383407"),
    ("BR-30", "Wetenschappelijk", "Martina Zelená, “The Commodification of Intimacy within Platform Capitalism”, Univerzita Karlova",
     "verdedigd 16 juni 2026", "dspace.cuni.cz/handle/20.500.11956/210238"),
    ("BR-31", "Wetgeving", "Richtlijn 2005/29/EG oneerlijke handelspraktijken (UCPD), art. 6–7 en bijlage I",
     "geconsolideerde tekst", "eur-lex.europa.eu/eli/dir/2005/29/oj"),
    ("BR-32", "Wetgeving", "Verordening (EU) 2016/679 (AVG), art. 5, 6, 9, 13–15 en 22",
     "geconsolideerde tekst", "eur-lex.europa.eu/eli/reg/2016/679/oj"),
    ("BR-33", "Wetgeving", "Verordening (EU) 2022/2065 (DSA), art. 25, 26 en 27",
     "geconsolideerde tekst", "eur-lex.europa.eu/eli/reg/2022/2065/oj"),
    ("BR-34", "Wetgeving", "Verordening (EU) 2024/1689 (AI-verordening), art. 50 + richtsnoeren Europese Commissie",
     "toepasselijk vanaf 2 augustus 2026", "ai-act-service-desk.ec.europa.eu"),
    ("BR-35", "Jaarcijfers", "Variety — Fenix International boekjaar 2024 (jaarrekening)",
     "Todd Spangler · 22 augustus 2025", "variety.com/2025/digital/news/1236495750/"),
    ("BR-36", "Jaarcijfers", "Variety en Forbes — Fenix International boekjaar 2023",
     "6 september 2024", "variety.com/2024/digital/news/1236135425/"),
    ("BR-37", "Jaarcijfers", "The Guardian — dividenden en verkoopverkenning OnlyFans",
     "22 augustus 2025", "theguardian.com/business/2025/aug/22/onlyfans-owner-dividends-revenue-potential-sale"),
    ("BR-38", "Rechtspraak", "Landgericht Hamburg — verbod op betaalde ‘influencer-chats’ van Fanblast wegens misleiding",
     "december 2025, gerapporteerd 5 februari 2026", "watson.de/leben/digital/974191698"),
    ("BR-39", "Sectorbron (onbevestigd)", "meetanlora.com — kostenmodel voor chatter-bezetting",
     "leveranciersblog, geen onafhankelijke verificatie", "meetanlora.com/blog/onlyfans-chatter-cost-2026"),
]

SOURCE_INDEX = {s[0]: s for s in SOURCES}

CLAIMS = [
    ("CL-01", "VASTGESTELD",
     "Betaalde chatters voeren gesprekken uit naam van creators zonder dat de abonnee dat weet.",
     "BR-01, BR-06, BR-07, BR-08, BR-15, BR-16",
     "Reuters documenteerde de praktijk bij toppagina’s; WIRED, GQ en SRF werkten zelf als chatter; BBC sprak chatters."),
    ("CL-02", "VASTGESTELD",
     "Commerciële software voor agentschappen biedt segmentatie op bestedingsvermogen, massaberichten en AI-antwoorden.",
     "BR-23, BR-24, BR-25",
     "De functionaliteit staat letterlijk op de publieke productpagina’s; citaten in hoofdstuk 4."),
    ("CL-03", "VASTGESTELD",
     "Chatterwerk wordt grotendeels uitbesteed aan laagbetaalde arbeid buiten de EU en de VS.",
     "BR-06, BR-19, BR-20, BR-21",
     "BBC noteerde lonen onder 2 dollar per uur; Rappler en Nikkei documenteerden Filipijnse arbeidsomstandigheden."),
    ("CL-04", "VASTGESTELD",
     "Agentschappen nemen tussen de helft en twee derde van de inkomsten van creators.",
     "BR-05, BR-08, BR-14",
     "BBC: de helft. SWR/tagesschau: tot twee derde. Vice citeert een oprichter over 50–60 procent op berichten."),
    ("CL-05", "VASTGESTELD",
     "Creators verliezen in bepaalde contracten de feitelijke controle over hun eigen account en inkomsten.",
     "BR-05, BR-14, BR-22, BR-17",
     "Gedocumenteerde gevallen van wachtwoordwissels, uitbetaling aan derden en accountoverdracht."),
    ("CL-06", "GEDOCUMENTEERD",
     "Er zijn bedreigingen en chantage vanuit agentschappen richting creators vastgelegd.",
     "BR-05, BR-17",
     "BBC publiceerde een letterlijke dreiging; in België loopt een strafzaak. Individuele zaken, geen sectorbrede vaststelling."),
    ("CL-07", "VASTGESTELD",
     "Rechters en rechtbanken behandelen niet-gemelde chat-vervanging als mogelijke misleiding.",
     "BR-03, BR-04, BR-38",
     "Twee Amerikaanse class actions en een Duits verbod op betaalde pseudo-influencerchats."),
    ("CL-08", "VASTGESTELD",
     "AI-systemen genereren of suggereren antwoorden in gesprekken die als persoonlijk worden gepresenteerd.",
     "BR-02, BR-21, BR-24, BR-25",
     "Reuters beschreef de software; leveranciers adverteren er zelf mee."),
    ("CL-09", "GEDOCUMENTEERD",
     "Chatters houden persoonlijke gegevens van abonnees bij in gedeelde dossiers: relatiestatus, verlies, koopgedrag.",
     "BR-01, BR-07, BR-15, BR-16, BR-23",
     "Undercoververslagen beschrijven notitievelden; de CRM-leveranciers bieden de velden aan. Omvang per bureau onbekend."),
    ("CL-10", "GEDOCUMENTEERD",
     "Scripts sturen op emotionele binding vóór verkoop: de gesprekstechniek is geoefend, niet spontaan.",
     "BR-07, BR-15, BR-16",
     "Trainingsinstructies zijn door drie journalisten van binnenuit vastgelegd."),
    ("CL-11", "VASTGESTELD",
     "De platformeconomie erachter is groot en geconcentreerd: 7,22 miljard dollar aan fanbetalingen in 2024.",
     "BR-35, BR-36, BR-37",
     "Jaarrekening Fenix International: 4,63 miljoen creator-accounts, 377,5 miljoen fan-accounts."),
    ("CL-12", "VASTGESTELD",
     "De gemiddelde creator verdient weinig; de opbrengst is extreem scheef verdeeld.",
     "BR-36",
     "Bij 4,12 miljoen creator-accounts in 2023 lag de gemiddelde jaarlijkse uitbetaling rond 1.300 dollar."),
    ("CL-13", "BETWIST",
     "Het platform draagt medeverantwoordelijkheid voor niet-gemelde chat-vervanging.",
     "BR-03, BR-06",
     "Eisers stellen dat het platform ervan profiteert; het platform verwijst naar voorwaarden die de creator verantwoordelijk maken. Onder de rechter."),
    ("CL-14", "ONBEVESTIGD",
     "Agentschappen classificeren abonnees systematisch op psychische kwetsbaarheid.",
     "BR-01, BR-23, BR-24",
     "Notitievelden en scorefuncties bestaan aantoonbaar; een sectorbrede, doelgerichte kwetsbaarheidsclassificatie is niet aangetoond."),
    ("CL-15", "ONBEVESTIGD",
     "Micro-transacties op sociale platformen dienen op grote schaal als witwas- of cardingkanaal.",
     "—",
     "Er is in dit dossier geen enkele opsporings-, toezichts- of rechtbankbron die dit staaft. Tot die er is: geen bewering, maar een onderzoeksvraag."),
    ("CL-16", "ONBEVESTIGD",
     "De sector veroorzaakt meetbare demografische effecten (geboortecijfers, relatievorming).",
     "—",
     "Er bestaat geen studie die een causaal verband legt. Correlaties met eenzaamheidscijfers volstaan niet."),
    ("CL-17", "HYPOTHESE",
     "De bedrijfstak profiteert van maatschappelijk wantrouwen dat zij deels zelf voedt.",
     "BR-26, BR-29",
     "Interpretatiekader van de auteur, geïnspireerd op onderzoek naar commodificatie. Geen feitelijke vaststelling."),
    ("CL-18", "HYPOTHESE",
     "Volledige zelf-commodificatie verandert het karakter van intimiteit zelf, ook buiten het platform.",
     "BR-26, BR-27, BR-30",
     "Brasseur noemt dit ‘total self-commodification’. Sociologisch concept, geen bewezen maatschappelijk effect."),
    ("CL-19", "VASTGESTELD",
     "De AI-verordening verplicht vanaf 2 augustus 2026 om te melden dat een gebruiker met AI praat.",
     "BR-34",
     "Art. 50, lid 1. De verplichting dekt AI-interactie, niet de menselijke plaatsvervanger."),
    ("CL-20", "VASTGESTELD",
     "Er bestaat een juridische lacune voor menselijke identiteitsvervanging in betaalde chat.",
     "BR-31, BR-34",
     "Het consumentenrecht werkt via de norm ‘misleidende praktijk’ per geval; een expliciete meldplicht ontbreekt."),
]

TIMELINE = [
    ("2021", "NRC beschrijft ‘eWhoring’: nepprofielen met van internet geplukte foto’s, 1,10 euro per profiel.", "BR-12"),
    ("nov 2022", "SWR/tagesschau documenteert Duitse agentschappen met commissies tot twee derde.", "BR-14"),
    ("okt 2023", "Vice publiceert het eerste uitgebreide portret van een chatter-agentschap.", "BR-08"),
    ("2023", "Eerste Amerikaanse class action tegen Fenix Internet over ‘authentieke relaties’.", "BR-04"),
    ("jan 2024", "SRF-journaliste wordt zelf opgeleid tot chatter en publiceert het trainingsmateriaal.", "BR-16"),
    ("mei 2024", "WIRED publiceert een undercoververslag vanuit het chatterwerk.", "BR-07"),
    ("juli 2024", "Reuters publiceert het onderzoek naar chat-vervanging en AI-software.", "BR-01, BR-02"),
    ("aug 2024", "Class action N.Z. e.a. v. Fenix International c.s. tegen platform én acht agentschappen.", "BR-03"),
    ("sep 2024", "Jaarcijfers 2023: 6,63 miljard dollar fanbetalingen, 4,12 miljoen creator-accounts.", "BR-36"),
    ("apr 2025", "Der Spiegel beschrijft de pseudo-intimiteit als bedrijfsmodel.", "BR-13"),
    ("jun 2025", "NRC legt een chat-callcenter in Manila bloot dat namens datingprofielen schrijft.", "BR-10, BR-11"),
    ("aug 2025", "Jaarcijfers 2024: 7,22 miljard dollar fanbetalingen; 497 miljoen dollar dividend.", "BR-35, BR-37"),
    ("nov 2025", "Balkan Insight documenteert een creator die van 178.000 dollar bruto 10.000 dollar ontving.", "BR-22"),
    ("dec 2025", "Landgericht Hamburg verbiedt betaalde chats met ‘vermeende influencers’ wegens misleiding.", "BR-38"),
    ("feb 2026", "Rappler documenteert Filipijnse editors en chatters: tarieven, intimidatie, onzekerheid.", "BR-19"),
    ("mrt 2026", "BBC beschrijft het chatterberoep van binnenuit: lonen onder twee dollar per uur.", "BR-06"),
    ("jun 2026", "BBC en The Guardian publiceren over dwang, dreiging en de handel in OFM-cursussen.", "BR-05, BR-09"),
    ("2 aug 2026", "Art. 50 AI-verordening wordt van toepassing: meldplicht bij AI-interactie.", "BR-34"),
    ("sep 2026", "Strafzaak in België tegen een ‘e-pooier’ rond een OnlyFans-creator.", "BR-17"),
]
