/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiefRouteImport } from './routes/archief'
import { Route as BoekRouteImport } from './routes/boek'
import { Route as BronnenRouteImport } from './routes/bronnen'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as FilosofieRouteImport } from './routes/filosofie'
import { Route as JuridischRouteImport } from './routes/juridisch'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as OnderzoekRouteImport } from './routes/onderzoek'
import { Route as OntkoppelingRouteImport } from './routes/ontkoppeling'
import { Route as BoekIndexRouteImport } from './routes/boek.index'
import { Route as BoekSlugRouteImport } from './routes/boek.$slug'
import { Route as DossierIndexRouteImport } from './routes/dossier.index'
import { Route as DossierSlugRouteImport } from './routes/dossier.$slug'
import { Route as HoofdstukSlugRouteImport } from './routes/hoofdstuk.$slug'
import { Route as JuridischIndexRouteImport } from './routes/juridisch.index'
import { Route as JuridischLexHumanitasRouteImport } from './routes/juridisch.lex-humanitas'
import { Route as OnderzoekIndexRouteImport } from './routes/onderzoek.index'
import { Route as OnderzoekSlugRouteImport } from './routes/onderzoek.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiefRoute = ArchiefRouteImport.update({
  id: '/archief',
  path: '/archief',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekRoute = BoekRouteImport.update({
  id: '/boek',
  path: '/boek',
  getParentRoute: () => rootRouteImport,
} as any)
const BronnenRoute = BronnenRouteImport.update({
  id: '/bronnen',
  path: '/bronnen',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const FilosofieRoute = FilosofieRouteImport.update({
  id: '/filosofie',
  path: '/filosofie',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridischRoute = JuridischRouteImport.update({
  id: '/juridisch',
  path: '/juridisch',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const OnderzoekRoute = OnderzoekRouteImport.update({
  id: '/onderzoek',
  path: '/onderzoek',
  getParentRoute: () => rootRouteImport,
} as any)
const OntkoppelingRoute = OntkoppelingRouteImport.update({
  id: '/ontkoppeling',
  path: '/ontkoppeling',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekIndexRoute = BoekIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoekRoute,
} as any)
const BoekSlugRoute = BoekSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BoekRoute,
} as any)
const DossierIndexRoute = DossierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DossierRoute,
} as any)
const DossierSlugRoute = DossierSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DossierRoute,
} as any)
const HoofdstukSlugRoute = HoofdstukSlugRouteImport.update({
  id: '/hoofdstuk/$slug',
  path: '/hoofdstuk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridischIndexRoute = JuridischIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JuridischRoute,
} as any)
const JuridischLexHumanitasRoute = JuridischLexHumanitasRouteImport.update({
  id: '/lex-humanitas',
  path: '/lex-humanitas',
  getParentRoute: () => JuridischRoute,
} as any)
const OnderzoekIndexRoute = OnderzoekIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnderzoekRoute,
} as any)
const OnderzoekSlugRoute = OnderzoekSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OnderzoekRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archief': typeof ArchiefRoute
  '/boek': typeof BoekRouteWithChildren
  '/bronnen': typeof BronnenRoute
  '/claims': typeof ClaimsRoute
  '/dossier': typeof DossierRouteWithChildren
  '/filosofie': typeof FilosofieRoute
  '/juridisch': typeof JuridischRouteWithChildren
  '/methodologie': typeof MethodologieRoute
  '/onderzoek': typeof OnderzoekRouteWithChildren
  '/ontkoppeling': typeof OntkoppelingRoute
  '/boek/$slug': typeof BoekSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/hoofdstuk/$slug': typeof HoofdstukSlugRoute
  '/juridisch/lex-humanitas': typeof JuridischLexHumanitasRoute
  '/onderzoek/$slug': typeof OnderzoekSlugRoute
  '/boek/': typeof BoekIndexRoute
  '/dossier/': typeof DossierIndexRoute
  '/juridisch/': typeof JuridischIndexRoute
  '/onderzoek/': typeof OnderzoekIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archief': typeof ArchiefRoute
  '/bronnen': typeof BronnenRoute
  '/claims': typeof ClaimsRoute
  '/filosofie': typeof FilosofieRoute
  '/methodologie': typeof MethodologieRoute
  '/ontkoppeling': typeof OntkoppelingRoute
  '/boek/$slug': typeof BoekSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/hoofdstuk/$slug': typeof HoofdstukSlugRoute
  '/juridisch/lex-humanitas': typeof JuridischLexHumanitasRoute
  '/onderzoek/$slug': typeof OnderzoekSlugRoute
  '/boek': typeof BoekIndexRoute
  '/dossier': typeof DossierIndexRoute
  '/juridisch': typeof JuridischIndexRoute
  '/onderzoek': typeof OnderzoekIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archief': typeof ArchiefRoute
  '/boek': typeof BoekRouteWithChildren
  '/bronnen': typeof BronnenRoute
  '/claims': typeof ClaimsRoute
  '/dossier': typeof DossierRouteWithChildren
  '/filosofie': typeof FilosofieRoute
  '/juridisch': typeof JuridischRouteWithChildren
  '/methodologie': typeof MethodologieRoute
  '/onderzoek': typeof OnderzoekRouteWithChildren
  '/ontkoppeling': typeof OntkoppelingRoute
  '/boek/$slug': typeof BoekSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/hoofdstuk/$slug': typeof HoofdstukSlugRoute
  '/juridisch/lex-humanitas': typeof JuridischLexHumanitasRoute
  '/onderzoek/$slug': typeof OnderzoekSlugRoute
  '/boek/': typeof BoekIndexRoute
  '/dossier/': typeof DossierIndexRoute
  '/juridisch/': typeof JuridischIndexRoute
  '/onderzoek/': typeof OnderzoekIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archief'
    | '/boek'
    | '/bronnen'
    | '/claims'
    | '/dossier'
    | '/filosofie'
    | '/juridisch'
    | '/methodologie'
    | '/onderzoek'
    | '/ontkoppeling'
    | '/boek/$slug'
    | '/dossier/$slug'
    | '/hoofdstuk/$slug'
    | '/juridisch/lex-humanitas'
    | '/onderzoek/$slug'
    | '/boek/'
    | '/dossier/'
    | '/juridisch/'
    | '/onderzoek/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archief'
    | '/bronnen'
    | '/claims'
    | '/filosofie'
    | '/methodologie'
    | '/ontkoppeling'
    | '/boek/$slug'
    | '/dossier/$slug'
    | '/hoofdstuk/$slug'
    | '/juridisch/lex-humanitas'
    | '/onderzoek/$slug'
    | '/boek'
    | '/dossier'
    | '/juridisch'
    | '/onderzoek'
  id:
    | '__root__'
    | '/'
    | '/archief'
    | '/boek'
    | '/bronnen'
    | '/claims'
    | '/dossier'
    | '/filosofie'
    | '/juridisch'
    | '/methodologie'
    | '/onderzoek'
    | '/ontkoppeling'
    | '/boek/$slug'
    | '/dossier/$slug'
    | '/hoofdstuk/$slug'
    | '/juridisch/lex-humanitas'
    | '/onderzoek/$slug'
    | '/boek/'
    | '/dossier/'
    | '/juridisch/'
    | '/onderzoek/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiefRoute: typeof ArchiefRoute
  BoekRoute: typeof BoekRouteWithChildren
  BronnenRoute: typeof BronnenRoute
  ClaimsRoute: typeof ClaimsRoute
  DossierRoute: typeof DossierRouteWithChildren
  FilosofieRoute: typeof FilosofieRoute
  JuridischRoute: typeof JuridischRouteWithChildren
  MethodologieRoute: typeof MethodologieRoute
  OnderzoekRoute: typeof OnderzoekRouteWithChildren
  OntkoppelingRoute: typeof OntkoppelingRoute
  HoofdstukSlugRoute: typeof HoofdstukSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archief': {
      id: '/archief'
      path: '/archief'
      fullPath: '/archief'
      preLoaderRoute: typeof ArchiefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boek': {
      id: '/boek'
      path: '/boek'
      fullPath: '/boek'
      preLoaderRoute: typeof BoekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bronnen': {
      id: '/bronnen'
      path: '/bronnen'
      fullPath: '/bronnen'
      preLoaderRoute: typeof BronnenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filosofie': {
      id: '/filosofie'
      path: '/filosofie'
      fullPath: '/filosofie'
      preLoaderRoute: typeof FilosofieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridisch': {
      id: '/juridisch'
      path: '/juridisch'
      fullPath: '/juridisch'
      preLoaderRoute: typeof JuridischRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onderzoek': {
      id: '/onderzoek'
      path: '/onderzoek'
      fullPath: '/onderzoek'
      preLoaderRoute: typeof OnderzoekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ontkoppeling': {
      id: '/ontkoppeling'
      path: '/ontkoppeling'
      fullPath: '/ontkoppeling'
      preLoaderRoute: typeof OntkoppelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boek/': {
      id: '/boek/'
      path: '/'
      fullPath: '/boek/'
      preLoaderRoute: typeof BoekIndexRouteImport
      parentRoute: typeof BoekRoute
    }
    '/boek/$slug': {
      id: '/boek/$slug'
      path: '/$slug'
      fullPath: '/boek/$slug'
      preLoaderRoute: typeof BoekSlugRouteImport
      parentRoute: typeof BoekRoute
    }
    '/dossier/': {
      id: '/dossier/'
      path: '/'
      fullPath: '/dossier/'
      preLoaderRoute: typeof DossierIndexRouteImport
      parentRoute: typeof DossierRoute
    }
    '/dossier/$slug': {
      id: '/dossier/$slug'
      path: '/$slug'
      fullPath: '/dossier/$slug'
      preLoaderRoute: typeof DossierSlugRouteImport
      parentRoute: typeof DossierRoute
    }
    '/hoofdstuk/$slug': {
      id: '/hoofdstuk/$slug'
      path: '/hoofdstuk/$slug'
      fullPath: '/hoofdstuk/$slug'
      preLoaderRoute: typeof HoofdstukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridisch/': {
      id: '/juridisch/'
      path: '/'
      fullPath: '/juridisch/'
      preLoaderRoute: typeof JuridischIndexRouteImport
      parentRoute: typeof JuridischRoute
    }
    '/juridisch/lex-humanitas': {
      id: '/juridisch/lex-humanitas'
      path: '/lex-humanitas'
      fullPath: '/juridisch/lex-humanitas'
      preLoaderRoute: typeof JuridischLexHumanitasRouteImport
      parentRoute: typeof JuridischRoute
    }
    '/onderzoek/': {
      id: '/onderzoek/'
      path: '/'
      fullPath: '/onderzoek/'
      preLoaderRoute: typeof OnderzoekIndexRouteImport
      parentRoute: typeof OnderzoekRoute
    }
    '/onderzoek/$slug': {
      id: '/onderzoek/$slug'
      path: '/$slug'
      fullPath: '/onderzoek/$slug'
      preLoaderRoute: typeof OnderzoekSlugRouteImport
      parentRoute: typeof OnderzoekRoute
    }
  }
}

interface BoekRouteChildren {
  BoekSlugRoute: typeof BoekSlugRoute
  BoekIndexRoute: typeof BoekIndexRoute
}

const BoekRouteChildren: BoekRouteChildren = {
  BoekSlugRoute: BoekSlugRoute,
  BoekIndexRoute: BoekIndexRoute,
}

const BoekRouteWithChildren = BoekRoute._addFileChildren(BoekRouteChildren)

interface DossierRouteChildren {
  DossierSlugRoute: typeof DossierSlugRoute
  DossierIndexRoute: typeof DossierIndexRoute
}

const DossierRouteChildren: DossierRouteChildren = {
  DossierSlugRoute: DossierSlugRoute,
  DossierIndexRoute: DossierIndexRoute,
}

const DossierRouteWithChildren =
  DossierRoute._addFileChildren(DossierRouteChildren)

interface JuridischRouteChildren {
  JuridischLexHumanitasRoute: typeof JuridischLexHumanitasRoute
  JuridischIndexRoute: typeof JuridischIndexRoute
}

const JuridischRouteChildren: JuridischRouteChildren = {
  JuridischLexHumanitasRoute: JuridischLexHumanitasRoute,
  JuridischIndexRoute: JuridischIndexRoute,
}

const JuridischRouteWithChildren = JuridischRoute._addFileChildren(
  JuridischRouteChildren,
)

interface OnderzoekRouteChildren {
  OnderzoekSlugRoute: typeof OnderzoekSlugRoute
  OnderzoekIndexRoute: typeof OnderzoekIndexRoute
}

const OnderzoekRouteChildren: OnderzoekRouteChildren = {
  OnderzoekSlugRoute: OnderzoekSlugRoute,
  OnderzoekIndexRoute: OnderzoekIndexRoute,
}

const OnderzoekRouteWithChildren = OnderzoekRoute._addFileChildren(
  OnderzoekRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiefRoute: ArchiefRoute,
  BoekRoute: BoekRouteWithChildren,
  BronnenRoute: BronnenRoute,
  ClaimsRoute: ClaimsRoute,
  DossierRoute: DossierRouteWithChildren,
  FilosofieRoute: FilosofieRoute,
  JuridischRoute: JuridischRouteWithChildren,
  MethodologieRoute: MethodologieRoute,
  OnderzoekRoute: OnderzoekRouteWithChildren,
  OntkoppelingRoute: OntkoppelingRoute,
  HoofdstukSlugRoute: HoofdstukSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
